import "./globals.css";
import Header from "./components/common/Header";
import AuthSession from "./AuthSession";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthSession>
                    <Header />
                    {children}
                </AuthSession>
            </body>
        </html>
    );
}
