import "./globals.css";
import Header from "./Header";
import AuthSession from "./AuthSession";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />
                <AuthSession>{children}</AuthSession>
            </body>
        </html>
    );
}
