const chocolate = [
    {
        name: "킨더 초콜릿 4개입",
        brand: "킨더",
        price: 1700,
        recommendation: 5,
        country: "이탈리아",
        flavor: "플레인",
        type: "밀크",
        description: `킨더 초콜릿은 부드러운 우유와 달콤한 밀크 초콜릿의 조화로 오랜 기간 아이들에게 사랑받고 있는 초콜릿입니다. \n낱개 포장으로 휴대가 간편하고, 나누어 먹기 좋은 작은 패키지로 구성되어 있습니다. \n어린아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/kinder.webp",
        url: "https://www.lotteon.com/p/product/LM0000080177609",
    },
    {
        name: "킨더 초콜릿 맥시 T-6",
        brand: "킨더",
        price: 4000,
        recommendation: 5,
        country: "이탈리아",
        flavor: "플레인",
        type: "밀크",
        description: `킨더 초콜릿은 부드러운 우유와 달콤한 밀크 초콜릿의 조화로 오랜 기간 아이들에게 사랑받고 있는 초콜릿입니다. \n킨더 초콜릿 맥시는 낱개 포장의 빅 사이즈 초콜릿으로 맛과 양적인 만족감을 제공합니다. \n어린아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/kinder_maxi.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000009027397",
    },
    {
        name: "킨더 초콜릿 미니 T-20",
        brand: "킨더",
        price: 4180,
        recommendation: 4,
        country: "이탈리아",
        flavor: "플레인",
        type: "밀크",
        description: `킨더 초콜릿은 부드러운 우유와 달콤한 밀크 초콜릿의 조화로 오랜 기간 아이들에게 사랑받고 있는 초콜릿입니다. \n킨더 초콜릿 미니는 한입에 쏙 들어가는 미니 사이즈의 초콜릿으로 낱개 포장되어 있습니다. \n어린아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/kinder_mini.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000055827176",
    },
    {
        name: "킨더 조이 걸",
        brand: "킨더",
        price: 2100,
        recommendation: 6,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "밀크",
        description: `킨더 조이는 달콤한 초콜릿과 장난감을 동시에 즐길 수 있는 초콜릿입니다. \n부드러운 우유 크림과 헤이즐넛 맛의 코코아 크림 속의 코코아 볼으로 달콤함과 식감까지 동시에 즐길 수 있습니다.\n어린아이들 선물로 추천드립니다.`,
        image: "/assets/chocolate/kinder_joy_girl.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000024919989",
    },
    {
        name: "킨더 조이 보이",
        brand: "킨더",
        price: 2100,
        recommendation: 6,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "밀크",
        description: `킨더 조이는 달콤한 초콜릿과 장난감을 동시에 즐길 수 있는 초콜릿입니다. \n부드러운 우유 크림과 헤이즐넛 맛의 코코아 크림 속의 코코아 볼으로 달콤함과 식감까지 동시에 즐길 수 있습니다.\n어린아이들 선물로 추천드립니다.`,
        image: "/assets/chocolate/kinder_joy_boy.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000024920056",
    },
    {
        name: "밀카 알프스 밀크 초콜릿",
        brand: "밀카",
        price: 3200,
        recommendation: 5,
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: `전 세계적으로 사랑받고 있는 밀카 초콜릿은 알프스의 최고급 우유로 만들어져 부드럽고 깊은 맛을 자랑합니다. \n밀카 알프스 밀크 초콜릿은 신선한 알프스 우유를 사용해 더욱 진하고 부드러운 맛을 느낄 수 있습니다. \n주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/milka_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031903349",
    },
    {
        name: "밀카 스트로베리",
        brand: "밀카",
        price: 3200,
        recommendation: 7,
        country: "독일",
        flavor: "딸기",
        type: "밀크",
        description: `전 세계적으로 사랑받고 있는 밀카 초콜릿은 알프스의 최고급 우유로 만들어져 부드럽고 깊은 맛을 자랑합니다. \n밀카 스트로베리는 부드러운 밀크 초콜릿 안에 상큼한 딸기 조각과 딸기 요거트 필링으로 채워져 있습니다. \n주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/milka_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031903346",
    },
    {
        name: "밀카 오레오",
        brand: "밀카",
        price: 3200,
        recommendation: 7,
        country: "독일",
        flavor: "오레오",
        type: "밀크",
        description: `전 세계적으로 사랑받고 있는 밀카 초콜릿은 알프스의 최고급 우유로 만들어져 부드럽고 깊은 맛을 자랑합니다. \n밀카 오레오는 부드러운 밀크 초콜릿 안에 바삭하고 달콤한 오레오 필링으로 채워져 있습니다. \n주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/milka_oreo.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031903347",
    },
    {
        name: "밀카 버블리",
        brand: "밀카",
        price: 3200,
        recommendation: 6,
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: `전 세계적으로 사랑받고 있는 밀카 초콜릿은 알프스의 최고급 우유로 만들어져 부드럽고 깊은 맛을 자랑합니다. \n밀카 버블리는 폭신폭신한 공기 기포가 더해져 재미있는 식감과 부드러움을 동시에 즐길 수 있습니다. \n주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/milka_bubbly.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=053612474&storeType=HYPER",
    },
    {
        name: "페레로 로쉐 3개입",
        brand: "페레로",
        price: 2700,
        recommendation: 4,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "프랄린",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 로쉐는 통 헤이즐넛을 감싼 헤이즐넛 크림과 바삭한 웨이퍼의 조화로 다채로운 식감과 풍미를 제공합니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_rocher_3.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000036668250",
    },
    {
        name: "페레로 콜렉션 T-9",
        brand: "페레로",
        price: 10600,
        recommendation: 5,
        country: "이탈리아",
        flavor: "믹스",
        type: "프랄린",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 콜렉션은 헤이즐넛 맛의 페레로 로쉐, 다크 초콜릿 필링의 페레로 란드누아, 코코넛과 화이트 초콜릿 조합의 라파엘로를 모두 맛볼 수 있는 컬렉션입니다. \n수험생 선물로도 인기가 많고, 소중한 사람들을 위한 선물로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_collection_t9.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000010370470",
    },
    {
        name: "페레로 로쉐 T8 하트",
        brand: "페레로",
        price: 9500,
        recommendation: 6,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "프랄린",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 로쉐는 통 헤이즐넛을 감싼 헤이즐넛 크림과 바삭한 웨이퍼의 조화로 다채로운 식감과 풍미를 제공합니다. \n하트 모양의 패키지로 특별한 날 연인이나 소중한 사람을 위한 선물로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_heart.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000006611231",
    },
    {
        name: "페레로 로쉐 T18 큐브",
        brand: "페레로",
        price: 18400,
        recommendation: 6,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "프랄린",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 로쉐는 통 헤이즐넛을 감싼 헤이즐넛 크림과 바삭한 웨이퍼의 조화로 다채로운 식감과 풍미를 제공합니다. \n선물 모양의 고급진 패키지로 어른들이나 소중한 사람을 위한 선물로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_cube.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000004715390",
    },
    {
        name: "노브랜드 다크 초콜릿",
        brand: "노브랜드",
        price: 980,
        recommendation: 5,
        country: "대한민국",
        flavor: "플레인",
        type: "다크",
        description: `초콜릿의 도시 벨기에에서 만들어진 노브랜드 초콜릿은 합리적인 가격과 좋은 재료로 많은 사랑을 받는 제품입니다. \n노브랜드 다크 초콜릿으로 깊고 진한 다크 초콜릿 본연의 맛을 즐길 수 있습니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/nobrand_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000532501706",
    },
    {
        name: "노브랜드 밀크 초콜릿",
        brand: "노브랜드",
        price: 980,
        recommendation: 5,
        country: "대한민국",
        flavor: "플레인",
        type: "밀크",
        description: `초콜릿의 도시 벨기에에서 만들어진 노브랜드 초콜릿은 합리적인 가격과 좋은 재료로 많은 사랑을 받는 제품입니다. \n노브랜드 밀크 초콜릿은 진하고 부드러운 풍미를 제공합니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/nobrand_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000532501707",
    },
    {
        name: "노브랜드 카라멜 아몬드 초콜릿",
        brand: "노브랜드",
        price: 1480,
        recommendation: 6,
        country: "대한민국",
        flavor: "아몬드",
        type: "밀크",
        description: `초콜릿의 도시 벨기에에서 만들어진 노브랜드 초콜릿은 합리적인 가격과 좋은 재료로 많은 사랑을 받는 제품입니다. \n노브랜드 카라멜 아몬드 초콜릿은 달콤한 카라멜 아몬드가 들어있어 맛과 식감을 동시에 제공합니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/nobrand_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000054980769",
    },
    {
        name: "토니스 밀크 초콜릿 헤이즐넛",
        brand: "토니스",
        price: 3400,
        recommendation: 6,
        country: "네덜란드",
        flavor: "헤이즐넛",
        type: "밀크",
        description: `네덜란드의 공정무역 초콜릿 브랜드인 토니스는 많은 나라에서 '착한 초콜릿'으로 사랑받고 있습니다. \n토니스 밀크 초콜릿 헤이즐넛은 부드러운 밀크 초콜릿에 고소한 헤이즐넛이 박혀있어 맛과 식감을 동시에 즐길 수 있는 제품입니다. \n주변 사람들에게 토니스의 맛과 메세지를 함께 전달해보세요.`,
        image: "/assets/chocolate/tonny's_hazelnut.webp",
        url: "https://emart.ssg.com/item/itemView.ssg?itemId=1000564930839",
    },
    {
        name: "토니스 다크 초콜릿",
        brand: "토니스",
        price: 3400,
        recommendation: 6,
        country: "네덜란드",
        flavor: "플레인",
        type: "다크",
        description: `네덜란드의 공정무역 초콜릿 브랜드인 토니스는 많은 나라에서 '착한 초콜릿'으로 사랑받고 있습니다. \n토니스 다크 초콜릿은 카카오 함량 70%로 초콜릿의 깊은 풍미를 느낄 수 있습니다. \n주변 사람들에게 토니스의 맛과 메세지를 함께 전달해보세요.`,
        image: "/assets/chocolate/tonny's_dark.webp",
        url: "https://emart.ssg.com/item/itemView.ssg?itemId=1000564930832",
    },
    {
        name: "토니스 다크 초콜릿 아몬드 씨솔트",
        brand: "토니스",
        price: 3400,
        recommendation: 6,
        country: "네덜란드",
        flavor: "아몬드",
        type: "다크",
        description: `네덜란드의 공정무역 초콜릿 브랜드인 토니스는 많은 나라에서 '착한 초콜릿'으로 사랑받고 있습니다. \n토니스 다크 초콜릿 아몬드 씨솔트는 진한 다크초콜릿에 아몬드 조각과 씨솔트의 조화로 달콤 짭짤한 맛을 느낄 수 있습니다. \n주변 사람들에게 토니스의 맛과 메세지를 함께 전달해보세요.`,
        image: "/assets/chocolate/tonny's_dark_almond.webp",
        url: "https://emart.ssg.com/item/itemDtl.ssg?itemId=1000564930834",
    },
    {
        name: "토니스 허니 아몬드 누가 밀크 초콜릿",
        brand: "토니스",
        price: 8900,
        recommendation: 7,
        country: "네덜란드",
        flavor: "누가",
        type: "밀크",
        description: `네덜란드의 공정무역 초콜릿 브랜드인 토니스는 많은 나라에서 '착한 초콜릿'으로 사랑받고 있습니다. \n토니스 허니 아몬드 누가 밀크 초콜릿에는 부드러운 밀크 초콜릿에 꿀, 아몬드, 누가 플레이크가 들어있어 한층 더 달콤한 풍미를 느낄 수 있습니다. \n주변 사람들에게 토니스의 맛과 메세지를 함께 전달해보세요.`,
        image: "/assets/chocolate/tonny's_honey_almond_nougat.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178949",
    },
    {
        name: "토니스 카라멜 씨솔트 밀크 초콜릿",
        brand: "토니스",
        price: 8900,
        recommendation: 7,
        country: "네덜란드",
        flavor: "카라멜",
        type: "밀크",
        description: `네덜란드의 공정무역 초콜릿 브랜드인 토니스는 많은 나라에서 '착한 초콜릿'으로 사랑받고 있습니다. \n토니스 카라멜 씨솔트 밀크 초콜릿은 부드러운 밀크 초콜릿과 달콤한 카라멜, 씨솔트의 조화로 네덜란드 내에서 가장 인기 있는 BEST 제품입니다. \n주변 사람들에게 토니스의 맛과 메세지를 함께 전달해보세요.`,
        image: "/assets/chocolate/tonny's_caramel_seasalt.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178954",
    },
    {
        name: "토니스 밀크 초콜릿",
        brand: "토니스",
        price: 8900,
        recommendation: 6,
        country: "네덜란드",
        flavor: "플레인",
        type: "밀크",
        description: `네덜란드의 공정무역 초콜릿 브랜드인 토니스는 많은 나라에서 '착한 초콜릿'으로 사랑받고 있습니다. \n토니스 밀크 초콜릿은 클래식하고 부드러운 맛을 가진 토니스의 시그니처 초콜릿입니다. \n주변 사람들에게 토니스의 맛과 메세지를 함께 전달해보세요.`,
        image: "/assets/chocolate/tonny's_milk.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178946",
    },
    {
        name: "부샤드 밀크 초콜릿",
        brand: "부샤드",
        price: 6300,
        recommendation: 5,
        country: "벨기에",
        flavor: "플레인",
        type: "밀크",
        description: `부샤드는 90년 전통의 벨기에 초콜릿 브랜드로, 한입에 쏙 들어가는 크기와 재료 본연의 맛으로 높은 평가를 받고 있습니다. \n부샤드 밀크 초콜릿은 입에서 사르르 녹는 부드러운 텍스쳐의 밀크 초콜릿입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/bouchard_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910032",
    },
    {
        name: "부샤드 다크 초콜릿 72%",
        brand: "부샤드",
        price: 6300,
        recommendation: 4,
        country: "벨기에",
        flavor: "플레인",
        type: "다크",
        description: `부샤드는 90년 전통의 벨기에 초콜릿 브랜드로, 한입에 쏙 들어가는 크기와 재료 본연의 맛으로 높은 평가를 받고 있습니다. \n부샤드 다크 초콜릿 72%는 일반 밀크 초콜릿 대비 설탕 함유량을 50% 줄여 다이어트 초콜릿으로도 인기 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/bouchard_dark.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=069579223&storeType=HYPER",
    },
    {
        name: "부샤드 카라멜&씨솔트 밀크 초콜릿",
        brand: "부샤드",
        price: 6300,
        recommendation: 8,
        country: "벨기에",
        flavor: "카라멜",
        type: "밀크",
        description: `부샤드는 90년 전통의 벨기에 초콜릿 브랜드로, 한입에 쏙 들어가는 크기와 재료 본연의 맛으로 높은 평가를 받고 있습니다. \n부샤드 카라멜&씨솔트 밀크 초콜릿은 씨솔트와 카라멜의 조화로 단짠 조합을 즐길 수 있어 가장 인기있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/bouchard_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910039",
    },
    {
        name: "린도볼 어쏘티드",
        brand: "린트",
        price: 18000,
        recommendation: 9,
        country: "스위스",
        flavor: "믹스",
        type: "믹스",
        description: `린트는 170년 이상의 스위스 프리미엄 초콜릿으로, 최상의 맛과 품질로 전 세계적인 사랑을 받는 브랜드입니다. \n린트 린도볼 어쏘티드는 밀크, 다크, 헤이즐넛, 화이트 네 가지 맛을 한 상자에 담은 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 진한 달콤함으로 젊은 층 선물이나 소중한 사람을 위한 선물로 추천드립니다.`,
        image: "/assets/chocolate/lindt_lindor_assorted.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000009001824",
    },
    {
        name: "린도볼 밀크",
        brand: "린트",
        price: 18000,
        recommendation: 8,
        country: "스위스",
        flavor: "플레인",
        type: "밀크",
        description: `린트는 170년 이상의 스위스 프리미엄 초콜릿으로, 최상의 맛과 품질로 전 세계적인 사랑을 받고 있는 브랜드입니다. \n린트 린도볼 밀크는 밀크 초콜릿 쉘 안에 부드러운 초콜릿 크림이 들어가 입안에서 사르르 녹는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고,  진한 달콤함으로 젊은 층 선물이나 소중한 사람을 위한 선물로도 추천드립니다.`,
        image: "/assets/chocolate/lindt_lindor_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000008044923",
    },
    {
        name: "린도볼 헤이즐넛",
        brand: "린트",
        price: 18000,
        recommendation: 8,
        country: "스위스",
        flavor: "헤이즐넛",
        type: "밀크",
        description: `린트는 170년 이상의 스위스 프리미엄 초콜릿으로, 최상의 맛과 품질로 전 세계적인 사랑을 받고 있는 브랜드입니다. \n린트 린도볼 헤이즐넛은 헤이즐넛 조각이 콕콕 박힌 밀크 초콜릿 쉘 안에 부드러운 크림이 들어가 고소하면서 달콤한 맛을 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 진한 달콤함으로 젊은 층 선물이나 소중한 사람을 위한 선물로도 추천드립니다.`,
        image: "/assets/chocolate/lindt_lindor_hazelnut.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000053878773",
    },
    {
        name: "린도볼 엑스트라 다크",
        brand: "린트",
        price: 18000,
        recommendation: 7,
        country: "스위스",
        flavor: "플레인",
        type: "다크",
        description: `린트는 170년 이상의 스위스 프리미엄 초콜릿으로, 최상의 맛과 품질로 전 세계적인 사랑을 받고 있는 브랜드입니다. \n린트 린도볼 다크는 카카오 함량 60%의 쌉쌀한 다크 초콜릿 쉘 안에 달콤한 초콜릿 크림이 들어있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 소중한 사람을 위한 선물로도 추천드립니다.`,
        image: "/assets/chocolate/lindt_lindor_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000010366851",
    },
    {
        name: "스위스 씬즈 밀크",
        brand: "린트",
        price: 16500,
        recommendation: 7,
        country: "스위스",
        flavor: "플레인",
        type: "밀크",
        description: `린트는 170년 이상의 스위스 프리미엄 초콜릿으로, 최상의 맛과 품질로 전 세계적인 사랑을 받고 있는 브랜드입니다. \n린트 스위스 씬즈 밀크는 2mm의 얇은 두께의 진한 다크 초콜릿으로 새로운 식감과 풍미를 선사합니다. \n깔끔한 맛으로 어른들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/lindt_thins_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000007942626",
    },
    {
        name: "스위스 씬즈 다크",
        brand: "린트",
        price: 16500,
        recommendation: 7,
        country: "스위스",
        flavor: "플레인",
        type: "다크",
        description: `린트는 170년 이상의 스위스 프리미엄 초콜릿으로, 최상의 맛과 품질로 전 세계적인 사랑을 받고 있는 브랜드입니다. \n린트 스위스 씬즈 다크는 2mm의 얇은 두께의 부드러운 다크 초콜릿으로 새로운 식감과 풍미를 선사합니다. \n깔끔한 맛으로 어른들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/lindt_thins_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000004456358",
    },
    {
        name: "리터 스포트 알파인 밀크 초콜릿",
        brand: "리터 스포트",
        price: 4500,
        recommendation: 5,
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 스포트 알파인 밀크 초콜릿은 알프스 우유와 헤이즐넛 페이스트가 들어가 부드럽고 깊은 풍미를 선사합니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000055970654",
    },
    {
        name: "리터 스포트 딸기 요거트 초콜릿",
        brand: "리터 스포트",
        price: 4500,
        recommendation: 6,
        country: "독일",
        flavor: "딸기",
        type: "밀크",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 스포트 딸기 요거트 초콜릿은 부드러운 밀크 초콜릿 안에 상큼한 딸기 요거트 크림이 들어있어 새콤달콤한 맛을 즐길 수 있는 제품입니다. \n상큼한 맛으로 젊은 층 선물이나 지인을 위한 가벼운 선물, 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000037012601",
    },
    {
        name: "리터 스포트 버터 비스킷 초콜릿",
        brand: "리터 스포트",
        price: 4500,
        recommendation: 7,
        country: "독일",
        flavor: "비스킷",
        type: "밀크",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 스포트 버터 비스킷 초콜릿은 부드러운 밀크 초콜릿 안에 버터 비스킷이 들어있어 고소하고 달콤한 풍미를 느낄 수 있는 제품입니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_biscuit.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000033967989",
    },
    {
        name: "리터 스포트 콘플레이크 초콜릿",
        brand: "리터 스포트",
        price: 4500,
        recommendation: 7,
        country: "독일",
        flavor: "콘플레이크",
        type: "밀크",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 스포트 콘플레이크 초콜릿은 부드러운 밀크 초콜릿 안에 바삭한 콘플레이크 조각이 들어있어 식감과 맛 모두 즐길 수 있는 제품입니다. \n강렬한 달콤함으로 젊은 층 선물이나 지인을 위한 가벼운 선물, 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_cornflakes.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040249541",
    },
    {
        name: "리터 미니 초콜릿 믹스 8p",
        brand: "리터 스포트",
        price: 7500,
        recommendation: 6,
        country: "독일",
        flavor: "믹스",
        type: "믹스",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 미니 초콜릿 믹스는 콘플레이크, 마지팬, 버터 비스킷, 프랄린, 알파인 밀크, 헤이즐넛 6가지 맛을 한 상자에 담은 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 소중한 사람을 위한 선물, 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_mini.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000518329649",
    },
    {
        name: "리터 초코큐브 요거트 러브",
        brand: "리터 스포트",
        price: 9900,
        recommendation: 7,
        country: "독일",
        flavor: "요거트",
        type: "믹스",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 초코큐브 요거트 러브는 딸기 요거트, 요거트, 블랙커런트 요거트 3가지 종류의 요거트 초콜릿으로 구성된 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 소중한 사람을 위한 선물, 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_love.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=127794260&storeType=HYPER",
    },
    {
        name: "리터 초코큐브 초콜릿 포유",
        brand: "리터 스포트",
        price: 9900,
        recommendation: 7,
        country: "독일",
        flavor: "믹스",
        type: "믹스",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 초코큐브 초콜릿 포유는 헤이즐넛 프랄린, 프랄린, 더블 카라멜, 초코 크리스프 4가지 종류의 초콜릿으로 구성된 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 소중한 사람을 위한 선물, 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_foryou.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=127794438&storeType=HYPER",
    },
    {
        name: "리터 초코큐브 땡큐",
        brand: "리터 스포트",
        price: 9900,
        recommendation: 7,
        country: "독일",
        flavor: "믹스",
        type: "믹스",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 초코큐브 초콜릿 포유는 더블 카라멜, 초콜릿 무스, 홀 헤이즐넛 프랄린, 초코 크리스피, 요거트 5가지 종류의 다양한 초콜릿으로 구성된 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹거나 소중한 사람을 위한 선물, 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_thank.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001525814",
    },
    {
        name: "몰티져스 밀크",
        brand: "몰티져스",
        price: 1500,
        recommendation: 4,
        country: "영국",
        flavor: "플레인",
        type: "밀크",
        description: `몰티져스는 중독적인 식감으로 인기 있는 글로벌 초콜릿 브랜드입니다. \n몰티져스 밀크는 동그란 크런치 볼을 밀크 초콜릿으로 감싸 바삭한 식감과 달콤한 맛을 함께 즐길 수 있는 제품입니다. \n주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/maltesers_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040900989",
    },
    {
        name: "몰티져스 다크",
        brand: "몰티져스",
        price: 1500,
        recommendation: 4,
        country: "영국",
        flavor: "플레인",
        type: "다크",
        description: `몰티져스는 중독적인 식감으로 인기 있는 글로벌 초콜릿 브랜드입니다. \n몰티져스 다크는 동그란 크런치 볼을 다크 초콜릿으로 감싸 바삭한 식감과 진한 다크 초콜릿의 맛을 함께 즐길 수 있는 제품입니다. \n주변 사람들과 나누어 먹거나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/maltesers_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040901013",
    },
    {
        name: "휘태커스 말보로 씨솔트&카라멜 밀크 초콜릿",
        brand: "휘태커스",
        price: 6500,
        recommendation: 6,
        country: "뉴질랜드",
        flavor: "카라멜",
        type: "밀크",
        description: `뉴질랜드의 국민 초콜릿 휘태커스는 최상의 품질로 많은 이들의 신뢰를 받는 초콜릿 브랜드입니다. \n휘태커스 말보로 씨솔트&카라멜 밀크 초콜릿은 부드러운 밀크 초콜릿에 카라멜 브리틀과 씨솔트로 식감과 풍미를 제공합니다. \n지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/whittaker's_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031039680",
    },
    {
        name: "휘태커스 넬슨 페어&마누카꿀 밀크 초콜릿",
        brand: "휘태커스",
        price: 6500,
        recommendation: 6,
        country: "뉴질랜드",
        flavor: "배",
        type: "밀크",
        description: `뉴질랜드의 국민 초콜릿 휘태커스는 최상의 품질로 많은 이들의 신뢰를 받는 초콜릿 브랜드입니다. \n휘태커스 넬슨 페어&마누카꿀 밀크 초콜릿은 부드러운 밀크 초콜릿에 쫀득한 배퓨레와 달콤한 마누카꿀이 들어가 새로운 식감과 맛을 제공합니다. \n지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/whittaker's_pear.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031039676",
    },
    {
        name: "휘태커스 웰링턴 로스티드 슈프림 커피 다크 초콜릿",
        brand: "휘태커스",
        price: 6500,
        recommendation: 5,
        country: "뉴질랜드",
        flavor: "커피",
        type: "다크",
        description: `뉴질랜드의 국민 초콜릿 휘태커스는 최상의 품질로 많은 이들의 신뢰를 받는 초콜릿 브랜드입니다. \n휘태커스 웰링턴 로스티드 슈프림 커피 다크 초콜릿은 커피 원두가 들어있어 쌉싸름하면서도 달콤한 풍미를 제공합니다. \n깊은 풍미로 어른들 선물로도 좋고, 지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/whittaker's_roasted_supreme_coffee.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000280759122",
    },
    {
        name: "칼파제르 셀렉션 초콜릿",
        brand: "칼파제르",
        price: 7000,
        recommendation: 5,
        country: "핀란드",
        flavor: "요거트",
        type: "밀크",
        description: `북유럽 대표 초콜릿인 칼파제르는 신선한 우유와 최상의 아리바 코코아를 사용해 부드럽고 진한 풍미를 자랑하는 브랜드입니다. \n칼파제르 셀렉션 초콜릿은 라즈베리 요거트와 블루베리 요거트 2가지 맛을 동시에 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 깔끔한 패키지로 지인 선물로도 추천드립니다.`,
        image: "/assets/chocolate/karl_fazer_selection.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521594820",
    },
    {
        name: "칼파제르 밀크 초콜릿",
        brand: "칼파제르",
        price: 7000,
        recommendation: 4,
        country: "핀란드",
        flavor: "플레인",
        type: "밀크",
        description: `북유럽 대표 초콜릿인 칼파제르는 신선한 우유와 최상의 아리바 코코아를 사용해 부드럽고 진한 풍미를 자랑하는 브랜드입니다. \n칼파제르 밀크 초콜릿은 타사 초콜릿 대비 설탕 함유량을 줄여 안심하고 먹을 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 깔끔한 패키지로 지인 선물로도 추천드립니다.`,
        image: "/assets/chocolate/karl_fazer_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000524075862",
    },
    {
        name: "칼파제르 다크 초콜릿",
        brand: "칼파제르",
        price: 7000,
        recommendation: 4,
        country: "핀란드",
        flavor: "플레인",
        type: "다크",
        description: `북유럽 대표 초콜릿인 칼파제르는 신선한 우유와 최상의 아리바 코코아를 사용해 부드럽고 진한 풍미를 자랑하는 브랜드입니다. \n칼파제르 다크 초콜릿은 70% 카카오 함유량으로 더욱 진하고 깊은 다크 초콜릿의 풍미를 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 깔끔한 패키지로 지인 선물로도 추천드립니다.`,
        image: "/assets/chocolate/karl_fazer_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521594036",
    },
    {
        name: "칼파제르 민트 필링 다크 초콜릿",
        brand: "칼파제르",
        price: 7000,
        recommendation: 4,
        country: "핀란드",
        flavor: "민트",
        type: "다크",
        description: `북유럽 대표 초콜릿인 칼파제르는 신선한 우유와 최상의 아리바 코코아를 사용해 부드럽고 진한 풍미를 자랑하는 브랜드입니다. \n칼파제르 민트 필링 다크 초콜릿은 다크 초콜릿 안에 민트 필링이 들어있어 상쾌하면서 달콤한 맛을 즐길 수 있는 제품입니다. \n민트 초콜릿이지만 당도가 높아 젊은 층 선물로 좋고, 개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋습니다.`,
        image: "/assets/chocolate/karl_fazer_mint.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521593546",
    },
    {
        name: "칼파제르 스트로베리 앤 바닐라 밀크 초콜릿",
        brand: "칼파제르",
        price: 7000,
        recommendation: 6,
        country: "핀란드",
        flavor: "딸기",
        type: "밀크",
        description: `북유럽 대표 초콜릿인 칼파제르는 신선한 우유와 최상의 아리바 코코아를 사용해 부드럽고 진한 풍미를 자랑하는 브랜드입니다. \n칼파제르 스트로베리 앤 바닐라 밀크 초콜릿은 부드러운 밀크 초콜릿에 상큼한 딸기 조각과 바닐라가 함유되어 있어 향긋한 풍미를 느낄 수 있는 제품입니다. \n지인 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/karl_fazer_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000059082238",
    },
    {
        name: "기라델리 스퀘어백 인텐스 다크 72% 카카오",
        brand: "기라델리",
        price: 13800,
        recommendation: 7,
        country: "미국",
        flavor: "플레인",
        type: "다크",
        description: `세계 3대 초콜릿 브랜드 중 하나인 기라델리는 오랜 역사와 전통을 자랑하는 미국의 대표 초콜릿 브랜드입니다. \n기라델리 스퀘어백 인텐스 다크 72% 카카오는 씁쓸하고 깊은 카카오 본연의 맛을 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 지인 선물이나 간식용으로도 추천드립니다.`,
        image: "/assets/chocolate/ghirardelli_dark_intense.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000055827174",
    },
    {
        name: "기라델리 스퀘어백 다크 초콜릿 씨솔트 카라멜",
        brand: "기라델리",
        price: 13800,
        recommendation: 9,
        country: "미국",
        flavor: "카라멜",
        type: "다크",
        description: `세계 3대 초콜릿 브랜드 중 하나인 기라델리는 오랜 역사와 전통을 자랑하는 미국의 대표 초콜릿 브랜드입니다. \n기라델리 스퀘어백 다크 초콜릿 씨솔트 카라멜은 깔끔한 다크 초콜릿 안에 달콤 짭짤한 씨솔트 카라멜이 들어있어 단짠의 조합을 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 진한 달콤함으로 젊은 층 선물이나 간식용으로도 추천드립니다.`,
        image: "/assets/chocolate/ghirardelli_dark_caramel_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000518329653",
    },
    {
        name: "기라델리 스퀘어백 밀크 초콜릿 카라멜",
        brand: "기라델리",
        price: 13800,
        recommendation: 9,
        country: "미국",
        flavor: "카라멜",
        type: "밀크",
        description: `세계 3대 초콜릿 브랜드 중 하나인 기라델리는 오랜 역사와 전통을 자랑하는 미국의 대표 초콜릿 브랜드입니다. \n기라델리 스퀘어백 밀크 초콜릿 카라멜은 부드러운 밀크 초콜릿 안에 진한 카라멜 필링을 채워 더욱 달콤한 맛을 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 진한 달콤함으로 젊은 층 선물이나 선물이나 간식용으로도 추천드립니다.`,
        image: "/assets/chocolate/ghirardelli_milk_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000518329656",
    },
    {
        name: "기라델리 씨솔트 아몬드",
        brand: "기라델리",
        price: 8000,
        recommendation: 7,
        country: "미국",
        flavor: "아몬드",
        type: "다크",
        description: `세계 3대 초콜릿 브랜드 중 하나인 기라델리는 오랜 역사와 전통을 자랑하는 미국의 대표 초콜릿 브랜드입니다. \n기라델리 씨솔트 아몬드는 다크 초콜릿과 씨솔트, 아몬드의 조화로 달콤 짭짤하면서 고소한 풍미를 느낄 수 있는 바 형식의 초콜릿입니다. \n소중한 사람을 위한 선물이나 간식으로 추천드립니다.`,
        image: "/assets/chocolate/ghirardelli_almond.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=052575432&storeType=HYPER",
    },
    {
        name: "기라델리 인텐스 다크 솔티드 카라멜",
        brand: "기라델리",
        price: 8000,
        recommendation: 8,
        country: "미국",
        flavor: "카라멜",
        type: "다크",
        description: `세계 3대 초콜릿 브랜드 중 하나인 기라델리는 오랜 역사와 전통을 자랑하는 미국의 대표 초콜릿 브랜드입니다. \n기라델리 인텐스 다크 솔티드 카라멜은 진한 다크 초콜릿에 카라멜과 소금이 풍미를 더해주는 바 형식의 초콜릿입니다. \n소중한 사람을 위한 선물이나 간식으로 추천드립니다.`,
        image: "/assets/chocolate/ghirardelli_salted_caramel.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=052575334&storeType=HYPER",
    },
    {
        name: "쇼게튼 알파인 밀크 초콜릿",
        brand: "쇼게튼",
        price: 3800,
        recommendation: 6,
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: `쇼게튼은 한입에 쏙 들어가는 조각 초콜릿 형태와 다양한 맛으로 인기 있는 초콜릿 브랜드입니다. \n쇼게튼 알파인 밀크 초콜릿은 고급 알프스 우유를 사용해 부드러운 식감을 선사합니다. \n조각으로 나누어져 있어 나누어 먹기에 좋고, 지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/schogetten_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001076538",
    },
    {
        name: "쇼게튼 요거트 스트로베리 초콜릿",
        brand: "쇼게튼",
        price: 3800,
        recommendation: 7,
        country: "독일",
        flavor: "딸기",
        type: "밀크",
        description: `쇼게튼은 한입에 쏙 들어가는 조각 초콜릿 형태와 다양한 맛으로 인기 있는 초콜릿 브랜드입니다. \n쇼게튼 요거트 스트로베리 초콜릿은 부드러운 밀크 초콜릿 안에 딸기 요거트 필링이 채워져 상큼함을 느낄 수 있습니다. \n조각으로 나누어져 있어 나누어 먹기에 좋고, 지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/schogetten_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001235591",
    },
    {
        name: "쇼게튼 블랙 앤 화이트",
        brand: "쇼게튼",
        price: 3800,
        recommendation: 7,
        country: "독일",
        flavor: "쿠키",
        type: "밀크",
        description: `쇼게튼은 한입에 쏙 들어가는 조각 초콜릿 형태와 다양한 맛으로 인기 있는 초콜릿 브랜드입니다. \n쇼게튼 블랙 앤 화이트는 밀크 초콜릿 안에 쿠키 앤 크림 맛의 크림이 채워져 더욱 부드럽고 달콤한 맛을 느낄 수 있는 제품입니다. \n조각으로 나누어져 있어 나누어 먹기에 좋고, 지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/schogetten_cookie.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001745526",
    },
    {
        name: "쇼게튼 포 키즈 위드 밀크",
        brand: "쇼게튼",
        price: 3800,
        recommendation: 6,
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: `쇼게튼은 한입에 쏙 들어가는 조각 초콜릿 형태와 다양한 맛으로 인기 있는 초콜릿 브랜드입니다. \n쇼게튼 포 키즈 위드 밀크는 어린이들을 위한 초콜릿으로 달콤한 밀크 초콜릿 안에 부드러운 우유 크림이 채워져 있습니다. \n조각으로 나누어져 있어 나누어 먹기에 좋고, 어린아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/schogetten_kids.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000280143063",
    },
    {
        name: "쇼게튼 다크 초콜릿 위드 헤이즐넛",
        brand: "쇼게튼",
        price: 3800,
        recommendation: 6,
        country: "독일",
        flavor: "헤이즐넛",
        type: "다크",
        description: `쇼게튼은 한입에 쏙 들어가는 조각 초콜릿 형태와 다양한 맛으로 인기 있는 초콜릿 브랜드입니다. \n쇼게튼 다크 초콜릿 위드 헤이즐넛은 진하고 고소한 다크 헤이즐넛 초콜릿으로 크런치한 식감까지 제공합니다. \n조각으로 나누어져 있어 나누어 먹기에 좋고, 지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/schogetten_hazelnuts.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=069698738&storeType=HYPER",
    },
    {
        name: "오설록 제주섬 녹차 초콜릿 바",
        brand: "오설록",
        price: 9900,
        recommendation: 6,
        country: "대한민국",
        flavor: "녹차",
        type: "다크",
        description: `오설록은 한국을 대표하는 프리미엄 차 브랜드이며 제주산 유기농 녹차를 넣은 오설록의 다양한 초콜릿도 세계적인 인기를 끌고 있습니다. \n오설록 제주섬 녹차 초콜릿 바는 깔끔한 다크 초콜릿 안에 진한 녹차 크림으로 채워져 쌉싸름하고 고급스러운 풍미를 느낄 수 있는 제품입니다. \n적당한 당도와 깊은 풍미로 어른들 선물로 추천드립니다.`,
        image: "/assets/chocolate/osulloc_chocolate_bar.webp",
        url: "https://www.osulloc.com/kr/ko/shop/item/bakery/6063",
    },
    {
        name: "오설록 제주섬 녹차 라즈베리 트러플",
        brand: "오설록",
        price: 13000,
        recommendation: 6,
        country: "대한민국",
        flavor: "녹차",
        type: "화이트",
        description: `오설록은 한국을 대표하는 프리미엄 차 브랜드이며 제주산 유기농 녹차를 넣은 오설록의 다양한 초콜릿도 세계적인 인기를 끌고 있습니다. \n오설록 제주섬 녹차 라즈베리 트러플은 진한 녹차 초콜릿 안에 상큼한 산딸기 크림이 들어있어 쌉싸름한 맛과 새콤달콤한 맛을 동시에 즐길 수 있는 제품입니다. \n적당한 당도와 깊은 풍미로 어른들 선물로 추천드립니다.`,
        image: "/assets/chocolate/osulloc_rasberry.webp",
        url: "https://www.osulloc.com/kr/ko/shop/item/bakery/18783",
    },
    {
        name: "오설록 제주섬 녹차 아몬드볼",
        brand: "오설록",
        price: 9000,
        recommendation: 5,
        country: "대한민국",
        flavor: "녹차",
        type: "화이트",
        description: `오설록은 한국을 대표하는 프리미엄 차 브랜드이며 제주산 유기농 녹차를 넣은 오설록의 다양한 초콜릿도 세계적인 인기를 끌고 있습니다. \n진한 녹차 초콜릿 안에 고소한 통 아몬드가 박혀있어 쌉쌀 달콤한 맛과 식감을 동시에 즐길 수 있는 제품입니다. \n적당한 당도와 깊은 풍미로 어른들 선물로 추천드립니다.`,
        image: "/assets/chocolate/osulloc_almond_ball.webp",
        url: "https://www.osulloc.com/kr/ko/shop/item/bakery/17803",
    },
    {
        name: "엠앤엠즈 피넛",
        brand: "엠앤엠즈",
        price: 1500,
        recommendation: 3,
        country: "미국",
        flavor: "피넛",
        type: "밀크",
        description: `엠앤엠즈는 알록달록한 색깔과 귀여운 캐릭터로 대중들에게 사랑을 받는 글로벌 초콜릿 브랜드입니다. \n엠앤엠즈 피넛은 컬러풀한 색으로 코팅된 밀크 초콜릿 속 고소한 땅콩이 들어있어 달콤한 맛과 바삭한 식감을 즐길 수 있는 제품입니다. \n어린 아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/m&m's_peanut.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000010706913",
    },
    {
        name: "엠앤엠즈 밀크",
        brand: "엠앤엠즈",
        price: 1500,
        recommendation: 2,
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: `엠앤엠즈는 알록달록한 색깔과 귀여운 캐릭터로 대중들에게 사랑을 받는 글로벌 초콜릿 브랜드입니다. \n엠앤엠즈 밀크는 컬러풀한 색으로 코팅된 밀크 초콜릿으로 부드러운 달콤함을 느낄 수 있는 제품입니다. \n어린 아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/m&m's_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000010706915",
    },
    {
        name: "엠앤엠즈 크리스피",
        brand: "엠앤엠즈",
        price: 1500,
        recommendation: 3,
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: `엠앤엠즈는 알록달록한 색깔과 귀여운 캐릭터로 대중들에게 사랑을 받는 글로벌 초콜릿 브랜드입니다. \n엠앤엠즈 크리스피는 바삭한 크런치 볼을 밀크 초콜릿과 컬러풀한 코팅이 감싸고 있어 식감과 맛을 함께 즐길 수 있는 제품입니다. \n어린 아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/m&m's_crispy.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000022024030",
    },
    {
        name: "엠앤엠즈 초콜릿 바 밀크",
        brand: "엠앤엠즈",
        price: 1500,
        recommendation: 2,
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: `엠앤엠즈는 알록달록한 색깔과 귀여운 캐릭터로 대중들에게 사랑을 받는 글로벌 초콜릿 브랜드입니다. \n엠앤엠즈 초콜릿 바 밀크는 밀크 초콜릿 속에 엠앤엠즈 초코볼이 들어있는 바 형식의 초콜릿으로 부드러운 밀크 초콜릿 사이 초코볼의 식감까지 즐길 수 있는 제품입니다. \n어린 아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/m&m's_bar_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000252587908",
    },
    {
        name: "엠앤엠즈 초콜릿 바 아몬드",
        brand: "엠앤엠즈",
        price: 1500,
        recommendation: 3,
        country: "미국",
        flavor: "아몬드",
        type: "밀크",
        description: `엠앤엠즈는 알록달록한 색깔과 귀여운 캐릭터로 대중들에게 사랑을 받는 글로벌 초콜릿 브랜드입니다. \n엠앤엠즈 초콜릿 바 아몬드는 고소한 아몬드 조각이 들어있는 밀크 초콜릿 속에 엠앤엠즈 초코볼이 들어있는 바 형식의 초콜릿입니다. \n어린 아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/m&m's_bar_almond.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000252587920",
    },
    {
        name: "엠앤엠즈 초콜릿 바 크리스피",
        brand: "엠앤엠즈",
        price: 1500,
        recommendation: 3,
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: `엠앤엠즈는 알록달록한 색깔과 귀여운 캐릭터로 대중들에게 사랑을 받는 글로벌 초콜릿 브랜드입니다. \n엠앤엠즈 초콜릿 바 크리스피는 크런치한 크리스피 라이스가 들어있는 밀크 초콜릿 속에 엠앤엠즈 초코볼이 들어있는 바 형식의 초콜릿입니다. \n어린 아이들 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/m&m's_bar_crispy.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000252587927",
    },
    {
        name: "앤디스 크림데 민트 띤",
        brand: "앤디스",
        price: 4900,
        recommendation: 5,
        country: "미국",
        flavor: "민트",
        type: "밀크",
        description: `민트 초콜릿으로 유명한 앤디스 초콜릿은 미국에서 식후 디저트로 사랑받고 있는 초콜릿 브랜드입니다. \n앤디스 크림데 민트 띤은 달콤한 밀크 초콜릿 사이에 상큼한 민트 크림이 샌드되어 있어 달콤하면서 청량한 맛을 느낄 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 민트를 좋아하는 주변 지인들에게도 선물해보세요.`,
        image: "/assets/chocolate/andes_creme_de_mint.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000004456287",
    },
    {
        name: "앤디스 민트 파르페 띤",
        brand: "앤디스",
        price: 4900,
        recommendation: 5,
        country: "미국",
        flavor: "민트",
        type: "화이트",
        description: `민트 초콜릿으로 유명한 앤디스 초콜릿은 미국에서 식후 디저트로 사랑받고 있는 초콜릿 브랜드입니다. \n앤디스 민트 파르페 띤은 상쾌한 민트 초콜릿 사이에 달콤한 밀크 초콜릿이 샌드되어 있어 시원하고 청량한 맛을 느낄 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 민트를 좋아하는 주변 지인들에게도 선물해보세요.`,
        image: "/assets/chocolate/andes_mint_parfait.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000004443",
    },
    {
        name: "앤디스 민트 쿠키크런치 띤",
        brand: "앤디스",
        price: 4900,
        recommendation: 4,
        country: "미국",
        flavor: "민트",
        type: "밀크",
        description: `민트 초콜릿으로 유명한 앤디스 초콜릿은 미국에서 식후 디저트로 사랑받고 있는 초콜릿 브랜드입니다. \n앤디스 민트 쿠키크런치 띤은 바삭한 쿠키 크런치가 들어있는 민트 초콜릿과 달콤한 밀크 초콜릿의 조화로 상큼함과 식감을 함께 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 민트를 좋아하는 주변 지인들에게도 선물해보세요.`,
        image: "/assets/chocolate/andes_cookie_crunch.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000192770",
    },
    {
        name: "앤디스 토피 크런치 띤",
        brand: "앤디스",
        price: 4900,
        recommendation: 5,
        country: "미국",
        flavor: "토피넛",
        type: "밀크",
        description: `민트 초콜릿으로 유명한 앤디스 초콜릿은 미국에서 식후 디저트로 사랑받고 있는 초콜릿 브랜드입니다. \n앤디스 토피 크런치 띤은 고소한 토피넛 초콜릿 속에 쿠키 크런치가 들어있어 달콤한 맛과 바삭한 식감을 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/andes_toffee_crunch.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000015859",
    },
    {
        name: "캐드베리 데어리밀크 버블리 밀크 초콜릿",
        brand: "캐드베리",
        price: 6000,
        recommendation: 6,
        country: "영국",
        flavor: "플레인",
        type: "밀크",
        description: `찰리와 초콜릿 공장의 모티브가 된 영국의 캐드베리는 빅토리아 여왕도 사랑한 초콜릿으로 명성 높은 초콜릿 브랜드입니다. \n캐드베리 데어리밀크 버블리 밀크 초콜릿은 부드러운 밀크 초콜릿 속 폭신한 공기층으로 독특한 식감과 부드러움을 제공하는 제품입니다. \n재미있는 식감으로 아이들이나 젊은 층 선물로도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/cadbury_bubbly.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000038260018",
    },
    {
        name: "리얼 다크 초콜릿 아몬드 바크씬",
        brand: "피코크",
        price: 7480,
        recommendation: 4,
        country: "대한민국",
        flavor: "아몬드",
        type: "다크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 다크 초콜릿 아몬드 바크씬은 진한 다크 초콜릿에 아몬드 분태를 넣은 씬 형태의 초콜릿으로 맛과 식감을 동시에 즐길 수 있는 제품입니다. \n여러 조각이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹기에도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/peacock_almond_bark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000010746553",
    },
    {
        name: "리얼 다크 초콜릿 쿠키 크런치 바크씬",
        brand: "피코크",
        price: 7480,
        recommendation: 5,
        country: "대한민국",
        flavor: "쿠키",
        type: "다크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 다크 초콜릿 쿠키 크런치 바크씬은 진한 다크 초콜릿에 바삭한 쿠키와 크런치가 들어있어 달콤한 맛과 식감을 즐길 수 있는 제품입니다. \n여러 조각이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹기에도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/peacock_cookie.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000038571762",
    },
    {
        name: "리얼 밀크 초콜릿 헤이즐넛 모카 바크씬",
        brand: "피코크",
        price: 7480,
        recommendation: 4,
        country: "대한민국",
        flavor: "헤이즐넛",
        type: "밀크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 밀크 초콜릿 헤이즐넛 모카 바크씬은 브라질 커피가 들어간 밀크 초콜릿에 바삭한 헤이즐넛 조각을 넣은 씬 형태의 초콜릿으로 깊고 고소한 풍미를 느낄 수 있는 제품입니다. \n여러 조각이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹기에도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/peacock_hazelnut.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000023360416",
    },
    {
        name: "리얼 밀크 초콜릿 카라멜 초코볼",
        brand: "피코크",
        price: 7480,
        recommendation: 6,
        country: "대한민국",
        flavor: "카라멜",
        type: "밀크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 밀크 초콜릿 카라멜 초코볼은 부드러운 밀크 초콜릿에 달콤한 카라멜 토피와 바삭한 라이스 크런치가 들어가 깊은 풍미와 식감을 느낄 수 있는 제품입니다. \n여러 조각이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹기에도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/peacock_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000051029055",
    },
    {
        name: "리얼 밀크 초콜릿 아몬드 크런치 초코볼",
        brand: "피코크",
        price: 8980,
        recommendation: 5,
        country: "대한민국",
        flavor: "아몬드",
        type: "밀크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 밀크 초콜릿 아몬드 크런치 초코볼은 고소한 통 아몬드를 라이스 크런치와 밀크 초콜릿으로 감싼 초코볼로 고소하고 달콤한 맛과 식감까지 즐길 수 있는 제품입니다. \n여러 개의 초코볼이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹기에도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/peacock_almond_ball.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000549087412",
    },
    {
        name: "리얼 초콜릿 아몬드 민트 초코볼",
        brand: "피코크",
        price: 8980,
        recommendation: 4,
        country: "대한민국",
        flavor: "민트",
        type: "화이트",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 초콜릿 아몬드 민트 초코볼은 고소한 통 아몬드를 상쾌한 민트 초콜릿으로 감싼 초코볼로 달콤함과 상쾌함을 즐길 수 있는 제품입니다. \n여러 개의 초코볼이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹거나 민트 초콜릿을 좋아하는 지인에게 선물해보세요.`,
        image: "/assets/chocolate/peacock_mint.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000200912199",
    },
    {
        name: "리얼 화이트 초콜릿 딸기",
        brand: "피코크",
        price: 7480,
        recommendation: 7,
        country: "대한민국",
        flavor: "딸기",
        type: "화이트",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n리얼 화이트 초콜릿 딸기는 상큼한 동결건조 딸기를 달콤한 화이트 초콜릿으로 감싼 초코볼로 새콤달콤한 풍미와 바삭한 식감을 함께 즐길 수 있는 제품입니다. \n여러 개의 초코볼이 지퍼백 안에 들어있어 주변 사람들과 나누어 먹기에도 좋고, 간식으로도 추천드립니다.`,
        image: "/assets/chocolate/peacock_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000053392894",
    },
    {
        name: "무설탕 초콜릿으로 만든 다크 70% 초코볼",
        brand: "피코크",
        price: 1980,
        recommendation: 2,
        country: "대한민국",
        flavor: "플레인",
        type: "다크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n무설탕 초콜릿으로 만든 다크 70% 초코볼은 무설탕 다크 초콜릿으로 적당한 당도와 깊은 다크 초콜릿의 풍미를 부담 없이 즐길 수 있는 초콜릿입니다. \n당 조절이나 식단 조절을 하는 지인 선물 혹은 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/peacock_no_sugar.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000036685034",
    },
    {
        name: "무설탕 초콜릿으로 만든 아몬드 초코볼",
        brand: "피코크",
        price: 2380,
        recommendation: 2,
        country: "대한민국",
        flavor: "아몬드",
        type: "다크",
        description: `피코크는 이마트의 프리미엄 PB 브랜드로 맛과 퀄리티가 높은 피코크의 초콜릿도 크게 사랑받고 있습니다. \n무설탕 초콜릿으로 만든 아몬드 초코볼은 고소한 통 아몬드를 무설탕 다크 초콜릿으로 감싼 초코볼로 오독한 식감과 적당한 달콤함을 느낄 수 있는 초콜릿입니다. \n당 조절이나 식단 조절을 하는 지인 선물 혹은 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/peacock_low_sugar.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000560499338",
    },
    {
        name: "지 큐브 다크 랩트 초콜릿 8개입",
        brand: "고디바",
        price: 17000,
        recommendation: 7,
        country: "벨기에",
        flavor: "플레인",
        type: "다크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n지 큐브 다크 랩트 초콜릿은 다크 초콜릿 쉘 안에 진한 다크 초콜릿 가나슈 필링이 들어있어 깊은 풍미를 느낄 수 있는 제품입니다. \n낱개 포장이 되어있어 가족이나 친구와 함께 나누어먹기 좋고, 나를 위한 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_gcube_dark.webp",
        url: "https://www.godiva.kr/item/7121208",
    },
    {
        name: "지 큐브 밀크 랩트 초콜릿 8개입",
        brand: "고디바",
        price: 17000,
        recommendation: 7,
        country: "벨기에",
        flavor: "플레인",
        type: "밀크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n지 큐브 밀크 랩트 초콜릿은 부드러운 밀크 초콜릿 쉘 안에 밀크 초콜릿 가나슈 필링이 들어있어 부드럽고 깊은 풍미를 느낄 수 있는 제품입니다. \n낱개 포장이 되어있어 가족이나 친구와 함께 나누어먹기 좋고, 나를 위한 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_gcube_milk.webp",
        url: "https://www.godiva.kr/item/7121108",
    },
    {
        name: "지 큐브 솔티드 캐러멜 랩트 초콜릿 8개입",
        brand: "고디바",
        price: 17000,
        recommendation: 7,
        country: "벨기에",
        flavor: "카라멜",
        type: "밀크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n지 큐브 밀크 랩트 초콜릿은 부드러운 밀크 초콜릿 쉘 안에 달콤 짭짤한 솔티드 캐러멜 가나슈 필링이 들어있어 단짠의 매력과 깊은 풍미를 느낄 수 있는 제품입니다. \n낱개 포장이 되어있어 가족이나 친구와 함께 나누어먹기 좋고, 나를 위한 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_gcube_salted_caramel.webp",
        url: "https://www.godiva.kr/item/7121408",
    },
    {
        name: "지 큐브 밀크 헤이즐넛 랩트 초콜릿 8개입",
        brand: "고디바",
        price: 17000,
        recommendation: 7,
        country: "벨기에",
        flavor: "헤이즐넛",
        type: "밀크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n지 큐브 밀크 랩트 초콜릿은 부드러운 밀크 초콜릿 쉘 안에 고소한 헤이즐넛 밀크 초콜릿 가나슈 필링이 들어있어 깊은 풍미를 느낄 수 있는 제품입니다. \n낱개 포장이 되어있어 가족이나 친구와 함께 나누어먹기 좋고, 나를 위한 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_gcube_hazelnut.webp",
        url: "https://www.godiva.kr/item/7121308",
    },
    {
        name: "골드 컬렉션 8개입",
        brand: "고디바",
        price: 30000,
        recommendation: 9,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n골드 컬렉션은 헤이즐넛, 카라멜, 가나슈 등의 다양한 필링으로 채워진 밀크, 다크, 화이트 초콜릿을 한 상자에 담아 다양한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 수험생 선물로 인기 있고, 특별한 날 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/godiva_gold_8.webp",
        url: "https://www.godiva.kr/item/3211108",
    },
    {
        name: "골드 컬렉션 12개입",
        brand: "고디바",
        price: 45000,
        recommendation: 10,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n골드 컬렉션은 헤이즐넛, 카라멜, 가나슈 등의 다양한 필링으로 채워진 밀크, 다크, 화이트 초콜릿을 한 상자에 담아 다양한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 수험생 선물로 인기 있고, 특별한 날 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/godiva_gold_collection_12.webp",
        url: "https://www.godiva.kr/item/3211112",
    },
    {
        name: "골드 컬렉션 20개입",
        brand: "고디바",
        price: 73000,
        recommendation: 10,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n골드 컬렉션은 헤이즐넛, 카라멜, 가나슈 등의 다양한 필링으로 채워진 밀크, 다크, 화이트 초콜릿을 한 상자에 담아 다양한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 수험생 선물로 인기 있고, 특별한 날 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/godiva_gold_20.webp",
        url: "https://www.godiva.kr/item/3211120",
    },
    {
        name: "골드 디스커버리 6개입",
        brand: "고디바",
        price: 32000,
        recommendation: 8,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n엘더버리 향, 장미 향의 가나슈 등 더욱 풍부하고 다양한 필링으로 채워진 밀크, 다크, 화이트 초콜릿을 한 상자에 담아 색다른 풍미를 느낄 수 있는 제품입니다. \n화려하고 고급진 패키지로 수험생 선물로 인기 있고, 특별한 날 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/godiva_discovery_6.webp",
        url: "https://www.godiva.kr/item/3211306",
    },
    {
        name: "골드 디스커버리 9개입",
        brand: "고디바",
        price: 42000,
        recommendation: 9,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n엘더버리 향, 장미 향의 가나슈 등 더욱 풍부하고 다양한 필링으로 채워진 밀크, 다크, 화이트 초콜릿을 한 상자에 담아 색다른 풍미를 느낄 수 있는 제품입니다. \n화려하고 고급진 패키지로 수험생 선물로 인기 있고, 특별한 날 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/godiva_discovery_9.webp",
        url: "https://www.godiva.kr/item/3211309",
    },
    {
        name: "골드 디스커버리 15개입",
        brand: "고디바",
        price: 65000,
        recommendation: 10,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n엘더버리 향, 장미 향의 가나슈 등 더욱 풍부하고 다양한 필링으로 채워진 밀크, 다크, 화이트 초콜릿을 한 상자에 담아 색다른 풍미를 느낄 수 있는 제품입니다. \n화려하고 고급진 패키지로 수험생 선물로 인기 있고, 특별한 날 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/godiva_discovery_15.webp",
        url: "https://www.godiva.kr/item/3211315",
    },
    {
        name: "레더라 컬렉션 18P",
        brand: "레더라",
        price: 67000,
        recommendation: 10,
        country: "스위스",
        flavor: "믹스",
        type: "프랄린",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n화려한 모양과 견과류, 누가, 초코 트러플 등의 필링이 들어있는 다양한 프랄린 초콜릿으로 눈과 입을 동시에 만족시켜주는 제품입니다. \n고급스러운 패키지와 맛으로 특별한 날 연인, 가족, 어른들을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_collection_18.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=L18",
    },
    {
        name: "레더라 컬렉션 24P",
        brand: "레더라",
        price: 88000,
        recommendation: 9,
        country: "스위스",
        flavor: "믹스",
        type: "프랄린",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n화려한 모양과 견과류, 누가, 초코 트러플 등의 필링이 들어있는 다양한 프랄린 초콜릿으로 눈과 입을 동시에 만족시켜주는 제품입니다. \n고급스러운 패키지와 맛으로 특별한 날 연인, 가족, 어른들을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_collection_24.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=L24",
    },
    {
        name: "레더라 컬렉션 4P",
        brand: "레더라",
        price: 17000,
        recommendation: 9,
        country: "스위스",
        flavor: "믹스",
        type: "프랄린",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n화려한 모양과 견과류, 누가, 초코 트러플 등의 필링이 들어있는 다양한 프랄린 초콜릿으로 눈과 입을 동시에 만족시켜주는 제품입니다. \n작은 패키지로 소중한 사람을 위한 선물이나 나를 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_collection_4.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=L4",
    },
    {
        name: "레더라 후리쉬쇼기 어쏘티드 박스",
        brand: "레더라",
        price: 45000,
        recommendation: 10,
        country: "스위스",
        flavor: "믹스",
        type: "믹스",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n캐러멜 라이즈드 된 통 견과류와 초콜릿이 절묘한 하모니를 이루며 다양한 식감과 맛을 선사합니다. \n특별한 날 연인, 친구, 가족들을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderach_assorted.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=1696406916",
    },
    {
        name: "후레쉬 초콜릿 모음 세트 320g",
        brand: "레더라",
        price: 56000,
        recommendation: 10,
        country: "스위스",
        flavor: "믹스",
        type: "믹스",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n캐러멜 라이즈드 된 통 견과류와 초콜릿이 절묘한 하모니를 이루며 다양한 식감과 맛을 선사합니다. \n특별한 날 연인, 친구, 가족들을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_fresh_320.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=1577432185",
    },
    {
        name: "후레쉬 초콜릿 모음 세트 220g",
        brand: "레더라",
        price: 40000,
        recommendation: 9,
        country: "스위스",
        flavor: "믹스",
        type: "믹스",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n캐러멜 라이즈드 된 통 견과류와 초콜릿이 절묘한 하모니를 이루며 다양한 식감과 맛을 선사합니다. \n특별한 날 연인, 친구, 가족들을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_fresh_220.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=1663654378",
    },
    {
        name: "프랄린 6P",
        brand: "레더라",
        price: 25000,
        recommendation: 8,
        country: "스위스",
        flavor: "믹스",
        type: "프랄린",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n견과류, 누가, 초코 트러플 등의 필링으로 채워진 다양한 프랄린 초콜릿으로 다채로운 풍미를 경험할 수 있습니다. \n작은 패키지로 소중한 사람을 위한 선물이나 나를 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_praline.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=L6",
    },
    {
        name: "파베 6P",
        brand: "레더라",
        price: 21000,
        recommendation: 7,
        country: "스위스",
        flavor: "플레인",
        type: "다크",
        description:
            "스위스 대표 최고급 수제 초콜릿 브랜드인 레더라는 최상의 재료와 신선한 맛으로 세계적인 사랑을 받고 있는 초콜릿 브랜드입니다. \n부드러운 아몬드 잔두야 가나슈를 코코아 파우더로 감싼 파베 초콜릿으로 입안에서 녹아내리는 식감과 달콤한 맛을 느낄 수 있는 제품입니다. \n소중한 사람을 위한 선물이나 나를 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/laderah_pave.webp",
        url: "https://kr.laderach.com/shop/item.php?it_id=P6",
    },
    {
        name: "노이하우스 밀크&다크&화이트 초콜릿 컬렉션 믹스 12P",
        brand: "노이하우스",
        price: 69000,
        recommendation: 10,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 중 하나인 노이하우스는 최초의 프랄린 초콜릿을 탄생시킨 역사 깊은 프리미엄 벨기에 초콜릿 브랜드입니다. \n누가틴, 헤이즐넛, 지안두자 등을 감싼 다양한 밀크, 다크, 화이트 프랄린 초콜릿으로 다채로운 풍미와 식감을 경험할 수 있습니다. \n고급스럽고 화려한 패키지와 깊은 풍미로 특별한 날 연인, 가족, 어른들 선물로 추천드립니다.",
        image: "/assets/chocolate/neuhaus_collection.webp",
        url: "https://smartstore.naver.com/neuhauschocolate_kr/products/8867194748",
    },
    {
        name: "노이하우스 듀엣 슬라이더 박스 36P",
        brand: "노이하우스",
        price: 93000,
        recommendation: 10,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 중 하나인 노이하우스는 최초의 프랄린 초콜릿을 탄생시킨 역사 깊은 프리미엄 벨기에 초콜릿 브랜드입니다. \n6가지 초콜릿 베이스와 6가지 토핑 중 하나씩 골라 믹스하여 먹는 제품으로 맛과 재미를 동시에 선사합니다. \n고급스러운 패키지와 재미있는 조화로 가족 선물로 추천드립니다.",
        image: "/assets/chocolate/neuhaus_duets.webp",
        url: "https://smartstore.naver.com/neuhauschocolate_kr/products/8867194204",
    },
    {
        name: "노이하우스 디스커버리 이리지스터블 초콜릿 5P",
        brand: "노이하우스",
        price: 35000,
        recommendation: 10,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 중 하나인 노이하우스는 최초의 프랄린 초콜릿을 탄생시킨 역사 깊은 프리미엄 벨기에 초콜릿 브랜드입니다. \n생크림과 가나슈를 누가틴으로 감싸 밀크, 다크, 화이트 초콜릿으로 코팅하여 진한 달콤함과 바삭한 식감까지 느낄 수 있는 초콜릿입니다. \n고급스러운 패키지와 새로운 맛으로 특별한 날 연인, 가족, 어른들 선물로 추천드립니다.",
        image: "/assets/chocolate/neuhaus_irresistibles.webp",
        url: "https://smartstore.naver.com/neuhauschocolate_kr/products/8867192910",
    },
    {
        name: "노이하우스 디스커버리 클래식 초콜릿 세트 6P",
        brand: "노이하우스",
        price: 35000,
        recommendation: 9,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 중 하나인 노이하우스는 최초의 프랄린 초콜릿을 탄생시킨 역사 깊은 프리미엄 벨기에 초콜릿 브랜드입니다. \n누가틴, 헤이즐넛, 견과류 등의 필링을 감싼 다양한 밀크, 다크, 화이트 프랄린 초콜릿으로 달콤하고 풍미 깊은 맛을 경험할 수 있습니다. \n고급스럽고 화려한 패키지로 특별한 날 연인, 가족, 어른들 선물로 추천드립니다.",
        image: "/assets/chocolate/neuhaus_classic.webp",
        url: "https://smartstore.naver.com/neuhauschocolate_kr/products/8867192703",
    },
    {
        name: "노이하우스 까레(CARRE) 다크&밀크 10가지 맛 60P",
        brand: "노이하우스",
        price: 75000,
        recommendation: 9,
        country: "벨기에",
        flavor: "믹스",
        type: "프랄린",
        description:
            "세계 3대 초콜릿 중 하나인 노이하우스는 최초의 프랄린 초콜릿을 탄생시킨 역사 깊은 프리미엄 벨기에 초콜릿 브랜드입니다. \n커피, 참깨, 라즈베리, 오렌지 등 10가지 맛의 초콜릿으로 다양한 풍미를 골라 즐길 수 있는 판 초콜릿 세트입니다. \n특별한 날 연인, 가족, 어른들 선물로 추천드립니다.",
        image: "/assets/chocolate/neuhaus_carre.webp",
        url: "https://smartstore.naver.com/neuhauschocolate_kr/products/8867193589",
    },
    {
        name: "부보 바르셀로나 마카다미아",
        brand: "부보",
        price: 32800,
        recommendation: 9,
        country: "스페인",
        flavor: "마카다미아",
        type: "화이트",
        description:
            "부보는 세계에서 가장 맛있는 초코케이크로 유명한 브랜드로, 스페인 바르셀로나 여행객들의 필수 방문지로 사랑받고 있습니다. \n부보 바르셀로나 마카다미아는 카라멜라이즈한 통 마카다미아를 바닐라 화이트 초콜릿으로 감싸고, 겉에 코코아 파우더와 꽃소금을 뿌려 극대화된 고소함과 달콤함을 느낄 수 있는 제품입니다. \n한입에 쏙 들어가는 초콜볼이 여러 개 들어있어 간식용으로도 좋고, 고급스러운 풍미로 가족과 함께 먹거나 어른들 선물으로 추천드립니다.",
        image: "/assets/chocolate/bubo_macadam.webp",
        url: "https://smartstore.naver.com/hfoodmarket/products/8266655080",
    },
    {
        name: "화이트살라미",
        brand: "트리투바",
        price: 14500,
        recommendation: 8,
        country: "대한민국",
        flavor: "기타",
        type: "화이트",
        description:
            "트리투바는 재료 선별부터 초콜릿 공정 과정까지 최상의 초콜릿을 위해 지속적인 연구개발을 하는 국내 초콜릿 브랜드입니다. \n화이트살라미는 이탈리아 훈제 소시지인 살라미를 연상시키는 모양으로 화이트 초콜릿에 건과일, 견과류가 들어있어 다양한 식감과 맛을 느낄 수 있는 제품입니다. \n특별한 날 와인과 함께 먹거나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/treetobar_white.webp",
        url: "https://smartstore.naver.com/hfoodmarket/products/8266655080",
    },
    {
        name: "밀크살라미",
        brand: "트리투바",
        price: 14500,
        recommendation: 6,
        country: "대한민국",
        flavor: "기타",
        type: "밀크",
        description:
            "트리투바는 재료 선별부터 초콜릿 공정 과정까지 최상의 초콜릿을 위해 지속적인 연구개발을 하는 국내 1세대 수제 초콜릿 브랜드입니다. \n밀크살라미는 이탈리아 훈제 소시지인 살라미를 연상시키는 모양으로 밀크 초콜릿에 견과류, 시나몬, 소금 등이 들어있어 다양한 식감과 맛을 느낄 수 있는 제품입니다. \n특별한 날 와인과 함께 먹거나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/treetobar_milk.webp",
        url: "https://smartstore.naver.com/treetobar/products/5315958476",
    },
    {
        name: "비건살라미",
        brand: "트리투바",
        price: 14500,
        recommendation: 6,
        country: "대한민국",
        flavor: "기타",
        type: "화이트",
        description:
            "트리투바는 재료 선별부터 초콜릿 공정 과정까지 최상의 초콜릿을 위해 지속적인 연구개발을 하는 국내 1세대 수제 초콜릿 브랜드입니다. \n비건살라미는 이탈리아 훈제 소시지인 살라미를 연상시키는 모양으로 비건 화이트 초콜릿에 건과일, 견과류가 들어있는 비건을 위한 초콜릿입니다. \n유제품 알러지가 있는 분이나 비건을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/treetobar_vegan.webp",
        url: "https://smartstore.naver.com/treetobar/products/6304094468",
    },
    {
        name: "크로캉 세트",
        brand: "트리투바",
        price: 23000,
        recommendation: 7,
        country: "대한민국",
        flavor: "믹스",
        type: "믹스",
        description:
            "트리투바는 재료 선별부터 초콜릿 공정 과정까지 최상의 초콜릿을 위해 지속적인 연구개발을 하는 국내 1세대 수제 초콜릿 브랜드입니다. \n크로캉 세트는 부드러운 초콜릿에 건과일, 견과류, 현미 크런치 등의 다양한 재료를 섞어 바삭한 화이트 크로캉, 밀크 크로캉을 한 박스로 즐길 수 있는 제품입니다. \n개별 박스 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 깔끔한 패키지와 고소한 풍미로 어른들 선물로도 추천합니다.",
        image: "/assets/chocolate/treetobar_croquant.webp",
        url: "https://smartstore.naver.com/treetobar/products/7368427165",
    },
    {
        name: "밀크 생초콜릿",
        brand: "김보람 초콜릿",
        price: 11000,
        recommendation: 7,
        country: "대한민국",
        flavor: "플레인",
        type: "밀크",
        description:
            "김보람 초콜릿은 쫀득하고 진한 생초콜릿으로 유명한 국내 수제 초콜릿 브랜드입니다. \n밀크 생초콜릿은 진한 밀크 초콜릿과 고소한 생크림을 섞어 부드럽고 달콤한 풍미와 쫀쫀한 식감을 느낄 수 있는 제품입니다. \n여러 조각의 초콜릿으로 간식용으로도 좋고, 수험생 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/kimboram_milk.webp",
        url: "https://smartstore.naver.com/kimboramchocolate/products/3583065645",
    },
    {
        name: "말차 생초콜릿",
        brand: "김보람 초콜릿",
        price: 12000,
        recommendation: 8,
        country: "대한민국",
        flavor: "녹차",
        type: "화이트",
        description:
            "김보람 초콜릿은 쫀득하고 진한 생초콜릿으로 유명한 국내 수제 초콜릿 브랜드입니다. \n말차 생초콜릿은 진한 말차가 들어가 쌉싸름하면서 달콤한 풍미와 쫀쫀한 식감을 느낄 수 있는 제품입니다. \n여러 조각의 초콜릿으로 간식용으로도 좋고, 수험생 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/kimboram_matcha.webp",
        url: "https://smartstore.naver.com/kimboramchocolate/products/3583065645",
    },
    {
        name: "다크 생초콜릿",
        brand: "김보람 초콜릿",
        price: 13000,
        recommendation: 7,
        country: "대한민국",
        flavor: "플레인",
        type: "다크",
        description:
            "김보람 초콜릿은 쫀득하고 진한 생초콜릿으로 유명한 국내 수제 초콜릿 브랜드입니다. \n다크 생초콜릿은 진한 다크 초콜릿에 고소한 생크림을 섞어 깊은 풍미와 쫀쫀한 식감을 느낄 수 있는 제품입니다. \n여러 조각의 초콜릿으로 간식용으로도 좋고, 수험생 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/kimboram_dark.webp",
        url: "https://smartstore.naver.com/kimboramchocolate/products/3583065645",
    },
    {
        name: "얼그레이 생초콜릿",
        brand: "김보람 초콜릿",
        price: 14000,
        recommendation: 6,
        country: "대한민국",
        flavor: "얼그레이",
        type: "화이트",
        description:
            "김보람 초콜릿은 쫀득하고 진한 생초콜릿으로 유명한 국내 수제 초콜릿 브랜드입니다. \n얼그레이 생초콜릿은 향긋한 얼그레이가 들어가 차의 풍미와 쫀쫀한 식감을 느낄 수 있는 제품입니다. \n여러 조각의 초콜릿으로 간식용으로도 좋고, 수험생 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/kimboram_earlgray.webp",
        url: "https://smartstore.naver.com/kimboramchocolate/products/3583065645",
    },
    {
        name: "아벨라나스 카라메리싸다스 레치",
        brand: "판크라시오",
        price: 17000,
        recommendation: 8,
        country: "스페인",
        flavor: "헤이즐넛",
        type: "화이트",
        description:
            "판크라시오는 최상의 맛과 디자인으로 초콜릿의 높은 퀄리티를 유지하는 스페인 프리미엄 초콜릿 브랜드입니다. \n아벨라나스 카라메리싸다스 레치는 카라멜라이즈 된 통 헤이즐넛을 화이트 초콜릿으로 감싸고 밀크 초콜릿 분말로 마무리해 고소하고 달콤한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 어른들 선물이나 연인, 가족 선물로 추천드립니다.",
        image: "/assets/chocolate/pancracio_avellanas.webp",
        url: "https://smartstore.naver.com/pancracio/products/8597036878",
    },
    {
        name: "로카스 수이자스 네그로",
        brand: "판크라시오",
        price: 17000,
        recommendation: 8,
        country: "스페인",
        flavor: "견과",
        type: "다크",
        description:
            "판크라시오는 최상의 맛과 디자인으로 초콜릿의 높은 퀄리티를 유지하는 스페인 프리미엄 초콜릿 브랜드입니다. \n로카스 수이자스 네그로는 다크 초콜릿에 캐러맬라이즈 된 아몬드, 헤이즐넛, 피스타치오가 들어가 고소하고 달콤한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 어른들 선물이나 연인, 가족 선물로 추천드립니다.",
        image: "/assets/chocolate/pancracio_rocas.webp",
        url: "https://smartstore.naver.com/pancracio/products/8597204552",
    },
    {
        name: "알멘드라스 카라메리싸다스 네그로",
        brand: "판크라시오",
        price: 17000,
        recommendation: 7,
        country: "스페인",
        flavor: "아몬드",
        type: "밀크",
        description:
            "판크라시오는 최상의 맛과 디자인으로 초콜릿의 높은 퀄리티를 유지하는 스페인 프리미엄 초콜릿 브랜드입니다. \n알멘드라스 카라메리싸다스 네그로는 카라멜라이즈 된 통 아몬드를 밀크 초콜릿으로 감싸고 다크 초콜릿 분말로 마무리해 고소하고 달콤한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 어른들 선물이나 연인, 가족 선물로 추천드립니다.",
        image: "/assets/chocolate/pancracio_almendras.webp",
        url: "https://smartstore.naver.com/pancracio/products/8597054783",
    },
    {
        name: "피스타초스 카라메리싸도스 레치",
        brand: "판크라시오",
        price: 17000,
        recommendation: 7,
        country: "스페인",
        flavor: "피스타치오",
        type: "밀크",
        description:
            "판크라시오는 최상의 맛과 디자인으로 초콜릿의 높은 퀄리티를 유지하는 스페인 프리미엄 초콜릿 브랜드입니다. \n피스타초스 카라메리싸도스 레치는 카라멜라이즈 된 피스타치오를 밀크 초콜릿으로 감싸 고소하고 달콤한 풍미를 느낄 수 있는 제품입니다. \n고급스러운 패키지로 어른들 선물이나 연인, 가족 선물로 추천드립니다.",
        image: "/assets/chocolate/pancracio_pistachos.webp",
        url: "https://smartstore.naver.com/pancracio/products/8596830265",
    },
    {
        name: "토피에츠",
        brand: "씨즈캔디",
        price: 82000,
        recommendation: 9,
        country: "미국",
        flavor: "토피넛",
        type: "밀크",
        description:
            "씨즈캔디는 캘리포니아에서 가장 오래되고 유명한 수제 디저트로 미국을 대표하는 디저트 브랜드입니다. \n토피에츠는 바삭한 버터 토피와 아몬드, 부드러운 밀크 초콜릿의 조화로 식감과 달콤함을 동시에 즐길 수 있는 제품입니다. \n진한 달콤함으로 젊은 층 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/see's_toffee_ettes.webp",
        url: "https://smartstore.naver.com/seescandies/products/584634472",
    },
    {
        name: "아몬드 클러스터",
        brand: "씨즈캔디",
        price: 50000,
        recommendation: 8,
        country: "미국",
        flavor: "아몬드",
        type: "밀크",
        description:
            "씨즈캔디는 캘리포니아에서 가장 오래되고 유명한 수제 디저트로 미국을 대표하는 디저트 브랜드입니다. \n아몬드 클러스터는 구운 아몬드를 달콤한 밀크 초콜릿이 감싸 바삭한 식감과 고소하고 부드러운 맛을 느낄 수 있는 제품입니다. \n견과의 고소한 풍미로 어른들 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/see's_almond_clusters.webp",
        url: "https://smartstore.naver.com/seescandies/products/608775340",
    },
    {
        name: "넛 클러스터",
        brand: "씨즈캔디",
        price: 32000,
        recommendation: 8,
        country: "미국",
        flavor: "아몬드",
        type: "밀크",
        description:
            "씨즈캔디는 캘리포니아에서 가장 오래되고 유명한 수제 디저트로 미국을 대표하는 디저트 브랜드입니다. \n넛 클러스터는 구운 아몬드를 달콤한 밀크 초콜릿이 감싸 바삭한 식감과 고소하고 부드러운 맛을 느낄 수 있는 제품입니다. \n견과의 고소한 풍미로 어른들 선물이나 소중한 사람을 위한 선물로 추천드립니다.",
        image: "/assets/chocolate/see's_nut_clusters.webp",
        url: "https://smartstore.naver.com/seescandies/products/7947683820",
    },
    {
        name: "토블론 스위스 다크 초콜릿",
        brand: "토블론",
        price: 4500,
        recommendation: 2,
        country: "스위스",
        flavor: "누가",
        type: "다크",
        description:
            "토블론은 150년 전통의 스위스 초콜릿 브랜드로 알프스 산맥을 닮은 시그니처 삼각형 모양이 특징입니다. \n토블론 스위스 다크 초콜릿은 쌉쌀한 다크 초콜릿에 달콤한 누가가 박혀있어 적당한 달콤함과 쌉쌀함이 조화를 이루는 초콜릿입니다. \n한 칸씩 나누어 먹기 편해 간식용으로도 좋고, 가벼운 선물용으로도 추천드립니다.",
        image: "/assets/chocolate/toblerone_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000008044472",
    },
    {
        name: "토블론 스위스 밀크 초콜릿",
        brand: "토블론",
        price: 4500,
        recommendation: 3,
        country: "스위스",
        flavor: "누가",
        type: "밀크",
        description:
            "토블론은 150년 전통의 스위스 초콜릿 브랜드로 알프스 산맥을 닮은 시그니처 삼각형 모양이 특징입니다. \n토블론 스위스 밀크 초콜릿은 부드러운 밀크 초콜릿에 누가, 아몬드가 박혀있어 진한 달콤함과 식감을 즐길 수 있는 제품입니다. \n한 칸씩 나누어 먹기 편해 간식용으로도 좋고, 가벼운 선물용으로도 추천드립니다.",
        image: "/assets/chocolate/toblerone_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000008333003",
    },
    {
        name: "토블론 스위스 화이트 초콜릿",
        brand: "토블론",
        price: 4500,
        recommendation: 3,
        country: "스위스",
        flavor: "누가",
        type: "화이트",
        description:
            "토블론은 150년 전통의 스위스 초콜릿 브랜드로 알프스 산맥을 닮은 시그니처 삼각형 모양이 특징입니다. \n토블론 스위스 화이트 초콜릿은 달콤하고 부드러운 화이트 초콜릿에 누가, 아몬드가 박혀있어 달콤함과 식감을 즐길 수 있는 제품입니다. \n한 칸씩 나누어 먹기 편해 간식용으로도 좋고, 가벼운 선물용으로도 추천드립니다.",
        image: "/assets/chocolate/toblerone_white.webp",
        url: "https://www.lotteon.com/p/product/LM7614500010310?sitmNo=LM7614500010310_001&mall_no=1",
    },
    {
        name: "기라델리 스퀘어백 인텐스 다크 씨솔트 스와레이",
        brand: "기라델리",
        price: 13800,
        recommendation: 8,
        country: "미국",
        flavor: "아몬드",
        type: "다크",
        description: `세계 3대 초콜릿 브랜드 중 하나인 기라델리는 오랜 역사와 전통을 자랑하는 미국의 대표 초콜릿 브랜드입니다. \n기라델리 씨솔트 스와레이는 깊은 다크 초콜릿에 아몬드와 씨솔트가 들어있어 깊은 풍미와 견과의 식감을 느낄 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에 좋고, 지인 선물이나 간식용으로도 추천드립니다.`,
        image: "/assets/chocolate/ghirardelli_intense_dark_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000019344507",
    },
    {
        name: "로스티드 아몬드 다크 초콜릿",
        brand: "고디바",
        price: 9900,
        recommendation: 7,
        country: "벨기에",
        flavor: "아몬드",
        type: "다크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n고디바 로스티드 아몬드 다크 초콜릿은 진한 다크 초콜릿에 로스티드 아몬드가 들어있어 깊은 맛과 식감을 동시에 즐길 수 있는 제품입니다. \n낱개 포장이 되어있어 간식용으로도 좋고, 지인 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_roasted_almond.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000280802100",
    },
    {
        name: "펄 밀크 초콜릿",
        brand: "고디바",
        price: 12000,
        recommendation: 8,
        country: "벨기에",
        flavor: "플레인",
        type: "밀크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n고디바 펄 밀크 초콜릿은 작은 진주 모양의 밀크 초콜릿으로 초콜릿의 깊은 풍미를 간편하게 즐길 수 있는 제품입니다. \n휴대하기 좋은 틴 케이스에 담겨있어 간식용으로도 좋고, 지인 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_pearl_milk.webp",
        url: "https://www.godiva.kr/item/136023",
    },
    {
        name: "펄 카푸치노 초콜릿",
        brand: "고디바",
        price: 12000,
        recommendation: 7,
        country: "벨기에",
        flavor: "커피",
        type: "밀크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n고디바 펄 카푸치노 초콜릿은 작은 진주 모양의 카푸치노 맛 밀크 초콜릿으로 초콜릿의 깊은 풍미를 간편하게 즐길 수 있는 제품입니다. \n휴대하기 좋은 틴 케이스에 담겨있어 간식용으로도 좋고, 지인 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_pearl_cappuccino.webp",
        url: "https://www.godiva.kr/item/136025",
    },
    {
        name: "펄 다크 초콜릿",
        brand: "고디바",
        price: 12000,
        recommendation: 7,
        country: "벨기에",
        flavor: "플레인",
        type: "다크",
        description:
            "세계 3대 초콜릿 브랜드 중 하나인 고디바 초콜릿은 최고급 초콜릿을 선보이는 벨기에 프리미엄 초콜릿 브랜드입니다. \n고디바 펄 다크 초콜릿은 작은 진주 모양의 다크 초콜릿으로 초콜릿의 깊은 풍미를 간편하게 즐길 수 있는 제품입니다. \n휴대하기 좋은 틴 케이스에 담겨있어 간식용으로도 좋고, 지인 선물로도 추천드립니다.",
        image: "/assets/chocolate/godiva_pearl_dark.webp",
        url: "https://www.godiva.kr/item/136024",
    },
    {
        name: "리터 스포트 다크 홀아몬드 초콜릿",
        brand: "리터 스포트",
        price: 4500,
        recommendation: 6,
        country: "독일",
        flavor: "아몬드",
        type: "다크",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 스포트 다크 홀아몬드 초콜릿은 진한 다크 초콜릿 안에 통 아몬드가 들어있어 쌉쌀하면서 고소한 풍미를 함께 느낄 수 있는 제품입니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_dark_almond.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000280759133",
    },
    {
        name: "리터 스포트 화이트 홀 헤이즐넛 초콜릿",
        brand: "리터 스포트",
        price: 4500,
        recommendation: 6,
        country: "독일",
        flavor: "헤이즐넛",
        type: "화이트",
        description: `100년 이상의 역사를 자랑하는 리터 스포트는 독일의 국민 초콜릿이라고도 불리는 초콜릿 브랜드입니다. \n리터 스포트 화이트 홀 헤이즐넛 초콜릿은 부드러운 화이트 초콜릿 안에 통 헤이즐넛이 들어가 진한 달콤함과 고소함을 동시에 느낄 수 있는 제품입니다. \n지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/rittersport_white_hazelnut.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=120981216&storeType=HYPER",
    },
    {
        name: "쇼게튼 화이트 초콜릿",
        brand: "쇼게튼",
        price: 3800,
        recommendation: 6,
        country: "독일",
        flavor: "플레인",
        type: "화이트",
        description: `쇼게튼은 한입에 쏙 들어가는 조각 초콜릿 형태와 다양한 맛으로 인기 있는 초콜릿 브랜드입니다. \n쇼게튼 화이트 초콜릿은 입에서 사르르 녹는 달콤한 화이트 초콜릿을 한입 크기로 즐길 수 있는 제품입니다. \n조각으로 나누어져 있어 나누어 먹기에 좋고, 지인을 위한 가벼운 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/schogetten_white.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=069698905&storeType=HYPER",
    },
    {
        name: "게이샤 다크 초콜릿",
        brand: "파제르",
        price: 7000,
        recommendation: 4,
        country: "핀란드",
        flavor: "헤이즐넛",
        type: "다크",
        description: `북유럽 대표 초콜릿인 파제르는 신선한 우유와 최상의 아리바 코코아를 사용해 부드럽고 진한 풍미를 자랑하는 브랜드입니다. \n게이샤 다크 초콜릿은 다크 초콜릿 안에 부드러운 헤이즐넛 필링이 들어있어 적당한 당도와 향긋한 풍미를 즐길 수 있는 제품입니다. \n개별 포장되어 있어 주변 사람들과 나누어 먹기에도 좋고, 간식용으로도 추천드립니다.`,
        image: "/assets/chocolate/geisha_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000037777854",
    },
    {
        name: "페레로 로쉐 오리지널 헤이즐넛",
        brand: "페레로",
        price: 7900,
        recommendation: 8,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "밀크",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 로쉐 오리지널 헤이즐넛은 부드러운 밀크 초콜릿에 고소한 헤이즐넛 필링이 채워져 깊은 풍미를 느낄 수 있는 제품입니다. \n지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_rocher_original.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000191124",
    },
    {
        name: "페레로 로쉐 화이트 헤이즐넛",
        brand: "페레로",
        price: 7900,
        recommendation: 8,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "화이트",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 로쉐 화이트 헤이즐넛은 달콤한 화이트 초콜릿에 고소한 헤이즐넛 필링이 채워져 진한 달콤함과 깊은 풍미를 느낄 수 있는 제품입니다. \n지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_rocher_white.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000191162",
    },
    {
        name: "페레로 로쉐 다크 헤이즐넛",
        brand: "페레로",
        price: 7900,
        recommendation: 7,
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "다크",
        description: `페레로는 오랜 시간 전 세계적으로 사랑받고 있는 이탈리아의 대표 브랜드입니다. \n페레로 로쉐 다크 헤이즐넛은 진한 다크 초콜릿에 부드러운 헤이즐넛 필링이 채워져 깊은 풍미를 느낄 수 있는 제품입니다. \n지인을 위한 선물이나 간식용으로 추천드립니다.`,
        image: "/assets/chocolate/ferrero_rocher_dark.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000191161",
    },
    {
        name: "아몬드 로카 캐니스터",
        brand: "아몬드 로카",
        price: 17900,
        recommendation: 8,
        country: "미국",
        flavor: "토피넛",
        type: "밀크",
        description: `아몬드 로카는 캘리포니아 아몬드와 신선한 버터의 풍미로 오랜 기간 사랑받고 있는 미국의 브랜드입니다. \n아몬드 로카 캐니스터는 달콤한 밀크 초콜릿 안에 아몬드 토피가 들어있어 크런치한 식감과 풍미를 즐길 수 있는 제품입니다. \n개별 포장되어 있어 간식용으로도 좋고, 선물용으로도 추천드립니다.`,
        image: "/assets/chocolate/almond_roca.webp",
        url: "https://smartstore.naver.com/almondroca/products/9455116641",
    },
    {
        name: "엑스트라 다크 로카 캐니스터",
        brand: "아몬드 로카",
        price: 17900,
        recommendation: 7,
        country: "미국",
        flavor: "토피넛",
        type: "다크",
        description: `아몬드 로카는 캘리포니아 아몬드와 신선한 버터의 풍미로 오랜 기간 사랑받고 있는 미국의 브랜드입니다. \n엑스트라 다크 로카 캐니스터는 진한 다크 초콜릿 안에 아몬드 토피가 들어있어 크런치한 식감과 달콤함을 즐길 수 있는 제품입니다. \n개별 포장되어 있어 간식용으로도 좋고, 선물용으로도 추천드립니다.`,
        image: "/assets/chocolate/extra_dark_roca.webp",
        url: "https://smartstore.naver.com/almondroca/products/9811367417",
    },
    {
        name: "화이트모카 35%",
        brand: "트리투바",
        price: 12000,
        recommendation: 6,
        country: "대한민국",
        flavor: "커피",
        type: "화이트",
        description:
            "트리투바는 재료 선별부터 초콜릿 공정 과정까지 최상의 초콜릿을 위해 지속적인 연구개발을 하는 국내 초콜릿 브랜드입니다. \n화이트모카 35% 초콜릿은 달콤하고 부드러운 화이트 초콜릿에 게이샤 커피빈이 들어가 향긋한 풍미를 느낄 수 있는 내츄럴 초콜릿입니다. \n깔끔한 포장으로 선물용으로도 좋고, 티타임 간식으로도 추천드립니다.",
        image: "/assets/chocolate/treetobar_white_mocha.webp",
        url: "https://smartstore.naver.com/treetobar/products/5895434673",
    },
    {
        name: "밀크웨딩 51%",
        brand: "트리투바",
        price: 12000,
        recommendation: 6,
        country: "대한민국",
        flavor: "홍차",
        type: "밀크",
        description:
            "트리투바는 재료 선별부터 초콜릿 공정 과정까지 최상의 초콜릿을 위해 지속적인 연구개발을 하는 국내 초콜릿 브랜드입니다. \n밀크웨딩 51% 초콜릿은 부드러운 밀크 초콜릿에 골든 아쌈티가 들어가 홍차의 풍미와 향을 느낄 수 있는 내츄럴 초콜릿입니다. \n깔끔한 포장으로 선물용으로도 좋고, 티타임 간식으로도 추천드립니다.",
        image: "/assets/chocolate/treetobar_milk_wedding.webp",
        url: "https://smartstore.naver.com/treetobar/products/5895425590",
    },
];

module.exports = chocolate;
