const chocolates = [
    {
        name: "킨더 초콜릿 4개입",
        brand: "킨더",
        price: "1700",
        country: "이탈리아",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/kinder.webp",
        url: "https://www.lotteon.com/p/product/LM0000080177609",
    },
    {
        name: "킨더 초콜릿 맥시 T-6",
        brand: "킨더",
        price: "4000",
        country: "이탈리아",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/kinder_maxi.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000009027397",
    },
    {
        name: "킨더 초콜릿 미니 T-20",
        brand: "킨더",
        price: "4180",
        country: "이탈리아",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/kinder_mini.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000055827176",
    },
    {
        name: "킨더 조이 걸",
        brand: "킨더",
        price: "2100",
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/kinder_joy_girl.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000024919989",
    },
    {
        name: "킨더 조이 보이",
        brand: "킨더",
        price: "2100",
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/kinder_joy_boy.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000024920056",
    },
    {
        name: "밀카 알프스 밀크 초콜릿",
        brand: "밀카",
        price: "3200",
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/milka_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031903349",
    },
    {
        name: "밀카 스트로베리 초콜릿",
        brand: "밀카",
        price: "3200",
        country: "독일",
        flavor: "딸기",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/milka_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031903346",
    },
    {
        name: "밀카 오레오 초콜릿",
        brand: "밀카",
        price: "3200",
        country: "독일",
        flavor: "오레오",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/milka_oreo.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031903347",
    },
    {
        name: "밀카 버블리 밀크 초콜릿",
        brand: "밀카",
        price: "3200",
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/milka_bubbly.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=053612474",
    },
    {
        name: "페레로 로쉐 3개입",
        brand: "페레로",
        price: "2700",
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "프랄린",
        description: "",
        image: "/assets/chocolate/ferrero_rocher_3.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000036668250",
    },
    {
        name: "페레로 로쉐 콜렉션 T-9",
        brand: "페레로",
        price: "10600",
        country: "이탈리아",
        flavor: "헤이즐넛",
        type: "프랄린",
        description: "",
        image: "/assets/chocolate/ferrero_collection_t9.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=0000010370470",
    },
    {
        name: "노브랜드 다크초콜릿",
        brand: "노브랜드",
        price: "980",
        country: "대한민국",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/nobrand_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000532501706",
    },
    {
        name: "노브랜드 밀크초콜릿",
        brand: "노브랜드",
        price: "980",
        country: "대한민국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/nobrand_milk",
        url: "",
    },
    {
        name: "노브랜드 카라멜아몬드초콜릿",
        brand: "노브랜드",
        price: "1480",
        country: "대한민국",
        flavor: "아몬드",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/nobrand_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000054980769",
    },
    {
        name: "토니스 헤이즐넛 초콜릿",
        brand: "토니스",
        price: "3400",
        country: "네덜란드",
        flavor: "헤이즐넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/tonny's_hazelnut.webp",
        url: "https://emart.ssg.com/item/itemView.ssg?itemId=1000564930839",
    },
    {
        name: "토니스 다크 초콜릿",
        brand: "토니스",
        price: "3400",
        country: "네덜란드",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/tonny's_dark.webp",
        url: "https://emart.ssg.com/item/itemView.ssg?itemId=1000564930832",
    },
    {
        name: "토니스 다크 아몬드 초콜릿",
        brand: "토니스",
        price: "3400",
        country: "네덜란드",
        flavor: "아몬드",
        type: "다크",
        description: "",
        image: "/assets/chocolate/tonny's_dark_almond.webp",
        url: "https://emart.ssg.com/item/itemDtl.ssg?itemId=1000564930834",
    },
    {
        name: "토니스 허니 아몬드 누가 밀크 초콜릿",
        brand: "토니스",
        price: "8900",
        country: "네덜란드",
        flavor: "누가",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/tonny's_honey_almond_nougat.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178949",
    },
    {
        name: "토니스 카라멜 씨솔트 밀크 초콜릿",
        brand: "토니스",
        price: "8900",
        country: "네덜란드",
        flavor: "카라멜",
        type: "다크",
        description: "",
        image: "/assets/chocolate/tonny's_caramel_seasalt.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178954",
    },
    {
        name: "토니스 밀크 초콜릿",
        brand: "토니스",
        price: "8900",
        country: "네덜란드",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/tonny's_milk.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178946",
    },
    {
        name: "부샤드 나폴리탄 밀크 초콜릿",
        brand: "부샤드",
        price: "6300",
        country: "벨기에",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/bouchard_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910032",
    },
    {
        name: "부샤드 나폴리탄 다크 72 초콜릿",
        brand: "부샤드",
        price: "6300",
        country: "벨기에",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/bouchard_dark.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=069579223",
    },
    {
        name: "부샤드 나폴리탄 카라멜&씨솔트 초콜릿",
        brand: "부샤드",
        price: "6300",
        country: "벨기에",
        flavor: "카라멜",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/bouchard_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910039",
    },
    {
        name: "린트 린도볼 어쏘티드",
        brand: "린트",
        price: "18000",
        country: "스위스",
        flavor: "믹스",
        type: "믹스",
        description: "",
        image: "/assets/chocolate/lindt_lindor_assorted.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910039",
    },
    {
        name: "린트 린도볼 밀크",
        brand: "린트",
        price: "18000",
        country: "스위스",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/lindt_lindor_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910039",
    },
    {
        name: "린트 린도볼 헤이즐넛",
        brand: "린트",
        price: "18000",
        country: "스위스",
        flavor: "헤이즐넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/lindt_lindor_hazelnut.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910039",
    },
    {
        name: "리터 스포트 알파인 밀크 초콜릿",
        brand: "리터 스포트",
        price: "4500",
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/rittersport_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000055970654",
    },
    {
        name: "리터 스포트 딸기 요거트 초콜릿",
        brand: "리터 스포트",
        price: "4500",
        country: "독일",
        flavor: "딸기",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/rittersport_strawberry_yogurt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000037012601",
    },
    {
        name: "리터 스포트 버터 비스킷 초콜릿",
        brand: "리터 스포트",
        price: "4500",
        country: "독일",
        flavor: "비스킷",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/rittersport_biscuit.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000520910039",
    },
    {
        name: "리터 스포트 콘플레이크 초콜릿",
        brand: "리터 스포트",
        price: "4500",
        country: "독일",
        flavor: "콘플레이크",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/rittersport_cornflakes.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040249541",
    },
    {
        name: "리터 미니 초콜릿믹스 8p",
        brand: "리터 스포트",
        price: "7500",
        country: "독일",
        flavor: "믹스",
        type: "믹스",
        description: "",
        image: "/assets/chocolate/rittersport_mini.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000518329649",
    },
    {
        name: "리터 초코큐브 요거트 러브",
        brand: "리터 스포트",
        price: "9900",
        country: "독일",
        flavor: "요거트",
        type: "믹스",
        description: "",
        image: "/assets/chocolate/rittersport_love.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=127794260",
    },
    {
        name: "리터 초코큐브 초콜릿 포유",
        brand: "리터 스포트",
        price: "9900",
        country: "독일",
        flavor: "믹스",
        type: "믹스",
        description: "",
        image: "/assets/chocolate/rittersport_foryou.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=127794438",
    },
    {
        name: "리터 초코큐브 땡큐",
        brand: "리터 스포트",
        price: "9900",
        country: "독일",
        flavor: "믹스",
        type: "믹스",
        description: "",
        image: "/assets/chocolate/rittersport_thank.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001525814",
    },
    {
        name: "몰티져스 밀크",
        brand: "몰티져스",
        price: "1500",
        country: "영국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/maltesers_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040900989",
    },
    {
        name: "몰티져스 다크",
        brand: "몰티져스",
        price: "1500",
        country: "영국",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/maltesers_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040901013",
    },
    {
        name: "휘태커스 씨쏠트&카라멜 밀크 초콜릿",
        brand: "몰티져스",
        price: "6500",
        country: "뉴질랜드",
        flavor: "카라멜",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/whittaker's_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031039680",
    },
    {
        name: "휘태커스 페어&마누카꿀 밀크 초콜릿",
        brand: "몰티져스",
        price: "6500",
        country: "뉴질랜드",
        flavor: "배",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/whittaker's_pear.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000031039676",
    },
    {
        name: "휘태커스 로스티드 슈프림 커피 다크 초콜릿",
        brand: "몰티져스",
        price: "6500",
        country: "뉴질랜드",
        flavor: "커피",
        type: "다크",
        description: "",
        image: "/assets/chocolate/whittaker's_roasted_supreme_coffee.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000280759122",
    },
    {
        name: "칼파제르 셀렉션 초콜릿",
        brand: "칼파제르",
        price: "7000",
        country: "핀란드",
        flavor: "믹스",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/karl_fazer_selection.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521594820",
    },
    {
        name: "칼파제르 밀크 초콜릿",
        brand: "칼파제르",
        price: "7000",
        country: "핀란드",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/karl_fazer_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000524075862",
    },
    {
        name: "칼파제르 다크 초콜릿",
        brand: "칼파제르",
        price: "7000",
        country: "핀란드",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/karl_fazer_dark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521594036",
    },
    {
        name: "칼파제르 민트 필링 다크 초콜릿",
        brand: "칼파제르",
        price: "7000",
        country: "핀란드",
        flavor: "민트",
        type: "다크",
        description: "",
        image: "/assets/chocolate/karl_fazer_mint.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521593546",
    },
    {
        name: "칼파제르 스트로베리",
        brand: "칼파제르",
        price: "7000",
        country: "핀란드",
        flavor: "딸기",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/karl_fazer_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000521594820",
    },
    {
        name: "기라델리 인텐스 다크 72% 스퀘어백",
        brand: "기라델리",
        price: "13800",
        country: "미국",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/ghirardelli_dark_intense.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000055827174",
    },
    {
        name: "기라델리 다크&카라멜 씨솔트 스퀘어백",
        brand: "기라델리",
        price: "13800",
        country: "미국",
        flavor: "카라멜",
        type: "다크",
        description: "",
        image: "/assets/chocolate/ghirardelli_dark_caramel_seasalt.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000518329653",
    },
    {
        name: "기라델리 밀크&카라멜 스퀘어백",
        brand: "기라델리",
        price: "13800",
        country: "미국",
        flavor: "카라멜",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/ghirardelli_milk_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000518329656",
    },
    {
        name: "기라델리 인텐스 다크 씨솔트 아몬드바",
        brand: "기라델리",
        price: "8000",
        country: "미국",
        flavor: "아몬드",
        type: "다크",
        description: "",
        image: "/assets/chocolate/ghirardelli_almond.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040645833",
    },
    {
        name: "기라델리 인텐스 다크 솔티드 카라멜바",
        brand: "기라델리",
        price: "8000",
        country: "미국",
        flavor: "카라멜",
        type: "다크",
        description: "",
        image: "/assets/chocolate/ghirardelli_salted_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000040645702",
    },
    {
        name: "쇼게튼 알파인 밀크 초콜릿",
        brand: "쇼게튼",
        price: "3800",
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/schogetten_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001076538",
    },
    {
        name: "쇼게튼 요거트 스트로베리 초콜릿",
        brand: "쇼게튼",
        price: "3800",
        country: "독일",
        flavor: "딸기",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/schogetten_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001235591",
    },
    {
        name: "쇼게튼 블랙&화이트 초콜릿",
        brand: "쇼게튼",
        price: "3800",
        country: "독일",
        flavor: "쿠키",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/schogetten_cookie.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=2097001745526",
    },
    {
        name: "쇼게튼 포 키즈 위드 밀크 초콜릿",
        brand: "쇼게튼",
        price: "3800",
        country: "독일",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/schogetten_kids.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000280143063",
    },
    {
        name: "쇼게튼 다크 초콜릿 위드 헤이즐넛 초콜릿",
        brand: "쇼게튼",
        price: "3800",
        country: "독일",
        flavor: "헤이즐넛",
        type: "다크",
        description: "",
        image: "/assets/chocolate/schogetten_hazelnuts.webp",
        url: "https://front.homeplus.co.kr/item?itemNo=069698738",
    },
    {
        name: "오설록 제주섬 녹차 초콜릿 바",
        brand: "오설록",
        price: "9900",
        country: "대한민국",
        flavor: "녹차",
        type: "다크",
        description: "",
        image: "/assets/chocolate/osulloc_chocolate_bar.webp",
        url: "https://www.osulloc.com/kr/ko/shop/item/bakery/6063",
    },
    {
        name: "오설록 제주섬 녹차 라즈베리 트러플",
        brand: "오설록",
        price: "13000",
        country: "대한민국",
        flavor: "녹차",
        type: "화이트",
        description: "",
        image: "/assets/chocolate/osulloc_rasberry.webp",
        url: "https://www.osulloc.com/kr/ko/shop/item/bakery/18783",
    },
    {
        name: "오설록 제주섬 녹차 아몬드볼",
        brand: "오설록",
        price: "9000",
        country: "대한민국",
        flavor: "녹차",
        type: "화이트",
        description: "",
        image: "/assets/chocolate/osulloc_almond_ball.webp",
        url: "https://www.osulloc.com/kr/ko/shop/item/bakery/17803",
    },
    {
        name: "엠앤엠즈 피넛",
        brand: "엠앤엠즈",
        price: "1500",
        country: "미국",
        flavor: "피넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/m&m's_peanut.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000010706913",
    },
    {
        name: "엠앤엠즈 밀크",
        brand: "엠앤엠즈",
        price: "1500",
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/m&m's_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000010706915",
    },
    {
        name: "엠앤엠즈 크리스피",
        brand: "엠앤엠즈",
        price: "1500",
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/m&m's_crispy.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000022024030",
    },
    {
        name: "엠앤엠즈 초콜릿 바 밀크",
        brand: "엠앤엠즈",
        price: "1500",
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/m&m's_bar_milk.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000252587908",
    },
    {
        name: "엠앤엠즈 초콜릿 바 아몬드",
        brand: "엠앤엠즈",
        price: "1500",
        country: "미국",
        flavor: "아몬드",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/m&m's_bar_almond.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000252587920",
    },
    {
        name: "엠앤엠즈 초콜릿 바 크리스피",
        brand: "엠앤엠즈",
        price: "1500",
        country: "미국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/m&m's_bar_crispy.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000252587927",
    },
    {
        name: "앤디스 크림드 민트 초콜릿",
        brand: "앤디스",
        price: "4900",
        country: "미국",
        flavor: "민트",
        type: "다크",
        description: "",
        image: "/assets/chocolate/andes_creme_de_mint",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000004456287",
    },
    {
        name: "앤디스 민트 파르페 초콜릿",
        brand: "앤디스",
        price: "4900",
        country: "미국",
        flavor: "민트",
        type: "다크",
        description: "",
        image: "/assets/chocolate/andes_mint_parfait.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000004456287",
    },
    {
        name: "앤디스 토피 크런치 초콜릿",
        brand: "앤디스",
        price: "4900",
        country: "미국",
        flavor: "토피넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/andes_toffee_crunch.webp",
        url: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000015859",
    },
    {
        name: "캐드베리 버블리 밀크 초콜릿",
        brand: "캐드베리",
        price: "6000",
        country: "영국",
        flavor: "플레인",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/cadbury_bubbly.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000038260018",
    },
    {
        name: "피코크 리얼 다크 초콜릿 아몬드 바크씬",
        brand: "피코크",
        price: "7480",
        country: "대한민국",
        flavor: "아몬드",
        type: "다크",
        description: "",
        image: "/assets/chocolate/peacock_almond_bark.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000010746553",
    },
    {
        name: "피코크 리얼 다크 초콜릿 쿠키 크런치 바크씬",
        brand: "피코크",
        price: "7480",
        country: "대한민국",
        flavor: "쿠키",
        type: "다크",
        description: "",
        image: "/assets/chocolate/peacock_cookie.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000038571762",
    },
    {
        name: "피코크 리얼 밀크 초콜릿 헤이즐넛 모카 바크씬",
        brand: "피코크",
        price: "7480",
        country: "대한민국",
        flavor: "헤이즐넛",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/peacock_hazelnut.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000023360416",
    },
    {
        name: "피코크 리얼 밀크 초콜릿 카라멜 초코볼",
        brand: "피코크",
        price: "7480",
        country: "대한민국",
        flavor: "카라멜",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/peacock_caramel.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000051029055",
    },
    {
        name: "피코크 리얼 밀크 초콜릿 아몬드 크런치 초코볼",
        brand: "피코크",
        price: "8980",
        country: "대한민국",
        flavor: "아몬드",
        type: "밀크",
        description: "",
        image: "/assets/chocolate/peacock_almond_ball.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000549087412",
    },
    {
        name: "피코크 리얼 초콜릿 아몬드 민트 초코볼",
        brand: "피코크",
        price: "8980",
        country: "대한민국",
        flavor: "민트",
        type: "화이트",
        description: "",
        image: "/assets/chocolate/peacock_mint.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000200912199",
    },
    {
        name: "피코크 리얼 화이트 초콜릿 딸기",
        brand: "피코크",
        price: "7480",
        country: "대한민국",
        flavor: "딸기",
        type: "화이트",
        description: "",
        image: "/assets/chocolate/peacock_strawberry.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000053392894",
    },
    {
        name: "피코크 무설탕 다크70% 초코볼",
        brand: "피코크",
        price: "1980",
        country: "대한민국",
        flavor: "플레인",
        type: "다크",
        description: "",
        image: "/assets/chocolate/peacock_no_sugar",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000036685034",
    },
    {
        name: "피코크 로우 슈거 아몬드 초코볼",
        brand: "피코크",
        price: "2380",
        country: "대한민국",
        flavor: "아몬드",
        type: "다크",
        description: "",
        image: "/assets/chocolate/peacock_low_sugar.webp",
        url: "https://www.ssg.com/item/itemView.ssg?itemId=1000560499338",
    },
];

export default chocolates;
